"""Made nullable


Revision ID: 0392c9f74bf4
Revises: 26681f80c5b4
Create Date: 2022-03-09 16:37:36.846937

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '0392c9f74bf4'
down_revision = '26681f80c5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reached_edge_heatmap_grid_calculation', 'start_perc',
               existing_type=sa.SMALLINT(),
               nullable=True,
               schema='customer')
    op.alter_column('reached_edge_heatmap_grid_calculation', 'end_perc',
               existing_type=sa.SMALLINT(),
               nullable=True,
               schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reached_edge_heatmap_grid_calculation', 'end_perc',
               existing_type=sa.SMALLINT(),
               nullable=False,
               schema='customer')
    op.alter_column('reached_edge_heatmap_grid_calculation', 'start_perc',
               existing_type=sa.SMALLINT(),
               nullable=False,
               schema='customer')
    # ### end Alembic commands ###
