"""changed foreign key

Revision ID: 05a8620ed15d
Revises: 97628bcd480b
Create Date: 2022-03-19 12:11:32.267521

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '05a8620ed15d'
down_revision = '97628bcd480b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer_library', sa.Column('style_library_name', sa.Text(), nullable=True), schema='customer')
    op.create_foreign_key(None, 'layer_library', 'style_library', ['style_library_name'], ['name'], source_schema='customer', referent_schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'layer_library', schema='customer', type_='foreignkey')
    op.drop_column('layer_library', 'style_library_name', schema='customer')
    # ### end Alembic commands ###
