"""changed datatype poi_uid

Revision ID: 061d24af05c8
Revises: 6239c44fdb81
Create Date: 2022-03-10 19:41:23.488166

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '061d24af05c8'
down_revision = '6239c44fdb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reached_poi_heatmap', 'poi_uid',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False,
               schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reached_poi_heatmap', 'poi_uid',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='customer')
    # ### end Alembic commands ###
