"""added layer and style library again

Revision ID: 066c60fbd96a
Revises: bc570bbc9294
Create Date: 2022-03-18 21:43:59.767548

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '066c60fbd96a'
down_revision = 'bc570bbc9294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
