"""added type fpr poi config

Revision ID: 16aa38de4035
Revises: fa649dc2dca0
Create Date: 2022-04-22 09:23:23.296973

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '16aa38de4035'
down_revision = 'fa649dc2dca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi_group', sa.Column('type', sa.Text(), nullable=False), schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poi_group', 'type', schema='basic')
    # ### end Alembic commands ###
