"""added active_data_upload_ids

Revision ID: 1ad086c93866
Revises: 08cd96697f87
Create Date: 2022-02-19 23:18:46.729676

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '1ad086c93866'
down_revision = '08cd96697f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_data_upload_ids', sa.ARRAY(sa.Integer()), server_default=sa.text("'{}'::int[]"), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_data_upload_ids', schema='customer')
    # ### end Alembic commands ###
