"""fixed typo in column name

Revision ID: 1c1cd1e80930
Revises: 9a71c3d6d26c
Create Date: 2022-04-24 12:44:27.069032

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '1c1cd1e80930'
down_revision = '9a71c3d6d26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_default_config', sa.Column('multiple_entrance', sa.Boolean(), nullable=True), schema='basic')
    op.drop_column('opportunity_default_config', 'multiple_entrace', schema='basic')
    op.add_column('opportunity_study_area_config', sa.Column('multiple_entrance', sa.Boolean(), nullable=True), schema='basic')
    op.drop_column('opportunity_study_area_config', 'multiple_entrace', schema='basic')
    op.add_column('opportunity_user_config', sa.Column('multiple_entrance', sa.Boolean(), nullable=True), schema='customer')
    op.drop_column('opportunity_user_config', 'multiple_entrace', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_user_config', sa.Column('multiple_entrace', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('opportunity_user_config', 'multiple_entrance', schema='customer')
    op.add_column('opportunity_study_area_config', sa.Column('multiple_entrace', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='basic')
    op.drop_column('opportunity_study_area_config', 'multiple_entrance', schema='basic')
    op.add_column('opportunity_default_config', sa.Column('multiple_entrace', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='basic')
    op.drop_column('opportunity_default_config', 'multiple_entrance', schema='basic')
    # ### end Alembic commands ###
