"""removed not needed table for isochrone edges

Revision ID: 22bd9ac33810
Revises: cbe1d8556ecf
Create Date: 2022-03-23 16:14:20.904653

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '22bd9ac33810'
down_revision = 'cbe1d8556ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
