"""Modified poi Ids

Revision ID: 23e90887b330
Revises: 85f55c00ab9f
Create Date: 2022-01-31 21:05:30.283768

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '23e90887b330'
down_revision = '85f55c00ab9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('uid', sa.Text(), nullable=False), schema='basic')
    op.drop_index('ix_basic_poi_scenario_id', table_name='poi', schema='basic')
    op.create_index(op.f('ix_basic_poi_uid'), 'poi', ['uid'], unique=False, schema='basic')
    op.create_unique_constraint(None, 'poi', ['uid'], schema='basic')
    op.drop_constraint('poi_scenario_id_fkey', 'poi', schema='basic', type_='foreignkey')
    op.drop_constraint('poi_poi_id_fkey', 'poi', schema='basic', type_='foreignkey')
    op.drop_column('poi', 'scenario_id', schema='basic')
    op.drop_column('poi', 'poi_id', schema='basic')
    op.add_column('poi_modified', sa.Column('uid', sa.Text(), nullable=False), schema='customer')
    op.add_column('poi_modified', sa.Column('edit_type', sa.Text(), nullable=False), schema='customer')
    op.add_column('poi_modified', sa.Column('table_name', sa.Text(), nullable=False), schema='customer')
    op.drop_index('ix_customer_poi_modified_poi_id', table_name='poi_modified', schema='customer')
    op.drop_index('ix_customer_poi_modified_poi_user_id', table_name='poi_modified', schema='customer')
    op.create_index(op.f('ix_customer_poi_modified_category'), 'poi_modified', ['category'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_poi_modified_edit_type'), 'poi_modified', ['edit_type'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_poi_modified_table_name'), 'poi_modified', ['table_name'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_poi_modified_uid'), 'poi_modified', ['uid'], unique=False, schema='customer')
    op.drop_constraint('poi_modified_poi_user_id_fkey', 'poi_modified', schema='customer', type_='foreignkey')
    op.drop_constraint('poi_modified_id_fkey', 'poi_modified', schema='customer', type_='foreignkey')
    op.drop_column('poi_modified', 'poi_user_id', schema='customer')
    op.drop_column('poi_modified', 'poi_id', schema='customer')
    op.add_column('poi_user', sa.Column('uid', sa.Text(), nullable=False), schema='customer')
    op.create_index(op.f('ix_customer_poi_user_uid'), 'poi_user', ['uid'], unique=False, schema='customer')
    op.create_unique_constraint(None, 'poi_user', ['uid', 'data_upload_id'], schema='customer')
    op.drop_constraint('poi_user_scenario_id_fkey', 'poi_user', schema='customer', type_='foreignkey')
    op.drop_column('poi_user', 'scenario_id', schema='customer')
    op.drop_column('poi_user', 'poi_user_id', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi_user', sa.Column('poi_user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='customer')
    op.add_column('poi_user', sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='customer')
    op.create_foreign_key('poi_user_scenario_id_fkey', 'poi_user', 'scenario', ['scenario_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_constraint(None, 'poi_user', schema='customer', type_='unique')
    op.drop_index(op.f('ix_customer_poi_user_uid'), table_name='poi_user', schema='customer')
    op.drop_column('poi_user', 'uid', schema='customer')
    op.add_column('poi_modified', sa.Column('poi_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='customer')
    op.add_column('poi_modified', sa.Column('poi_user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='customer')
    op.create_foreign_key('poi_modified_id_fkey', 'poi_modified', 'poi', ['id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    op.create_foreign_key('poi_modified_poi_user_id_fkey', 'poi_modified', 'poi_user', ['poi_user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_index(op.f('ix_customer_poi_modified_uid'), table_name='poi_modified', schema='customer')
    op.drop_index(op.f('ix_customer_poi_modified_table_name'), table_name='poi_modified', schema='customer')
    op.drop_index(op.f('ix_customer_poi_modified_edit_type'), table_name='poi_modified', schema='customer')
    op.drop_index(op.f('ix_customer_poi_modified_category'), table_name='poi_modified', schema='customer')
    op.create_index('ix_customer_poi_modified_poi_user_id', 'poi_modified', ['poi_user_id'], unique=False, schema='customer')
    op.create_index('ix_customer_poi_modified_poi_id', 'poi_modified', ['poi_id'], unique=False, schema='customer')
    op.drop_column('poi_modified', 'table_name', schema='customer')
    op.drop_column('poi_modified', 'edit_type', schema='customer')
    op.drop_column('poi_modified', 'uid', schema='customer')
    op.add_column('poi', sa.Column('poi_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='basic')
    op.add_column('poi', sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='basic')
    op.create_foreign_key('poi_poi_id_fkey', 'poi', 'poi', ['poi_id'], ['id'], source_schema='basic', referent_schema='basic', ondelete='CASCADE')
    op.create_foreign_key('poi_scenario_id_fkey', 'poi', 'scenario', ['scenario_id'], ['id'], source_schema='basic', referent_schema='customer', ondelete='CASCADE')
    op.drop_constraint(None, 'poi', schema='basic', type_='unique')
    op.drop_index(op.f('ix_basic_poi_uid'), table_name='poi', schema='basic')
    op.create_index('ix_basic_poi_scenario_id', 'poi', ['scenario_id'], unique=False, schema='basic')
    op.drop_column('poi', 'uid', schema='basic')
    # ### end Alembic commands ###
