"""added column building

Revision ID: 25d7b7610160
Revises: 2e06d4056b4a
Create Date: 2022-03-15 12:47:37.811326

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25d7b7610160'
down_revision = '2e06d4056b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poi_modified', 'scenario_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='customer')
    op.drop_column('way_modified', 'length_m', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('way_modified', sa.Column('length_m', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='customer')
    op.alter_column('poi_modified', 'scenario_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='customer')
    # ### end Alembic commands ###
