"""added user project link

Revision ID: 2b369bf7669a
Revises: b1a9547c023b
Create Date: 2023-09-02 14:33:13.030751

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b369bf7669a'
down_revision = 'b1a9547c023b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('initial_view_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['customer.project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['customer.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.drop_column('project', 'initial_view_state', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('initial_view_state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False), schema='customer')
    op.drop_table('user_project', schema='customer')
    # ### end Alembic commands ###
