"""added new column sub_study_area_id

Revision ID: 2c379f2b7db2
Revises: 36878c43943c
Create Date: 2022-02-17 08:40:50.494991

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '2c379f2b7db2'
down_revision = '36878c43943c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('population', sa.Column('sub_study_area_id', sa.Integer(), nullable=True), schema='basic')
    op.create_index(op.f('ix_basic_population_sub_study_area_id'), 'population', ['sub_study_area_id'], unique=False, schema='basic')
    op.add_column('population_modified', sa.Column('sub_study_area_id', sa.Integer(), nullable=True), schema='customer')
    op.create_index(op.f('ix_customer_population_modified_sub_study_area_id'), 'population_modified', ['sub_study_area_id'], unique=False, schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_population_modified_sub_study_area_id'), table_name='population_modified', schema='customer')
    op.drop_column('population_modified', 'sub_study_area_id', schema='customer')
    op.drop_index(op.f('ix_basic_population_sub_study_area_id'), table_name='population', schema='basic')
    op.drop_column('population', 'sub_study_area_id', schema='basic')
    # ### end Alembic commands ###
