"""study area buffer not nullabel

Revision ID: 2e06d4056b4a
Revises: 7d1a7713fae2
Create Date: 2022-03-12 15:39:09.751287

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '2e06d4056b4a'
down_revision = '7d1a7713fae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_area', 'buffer_geom_heatmap',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=False,
               schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_area', 'buffer_geom_heatmap',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=True,
               schema='basic')
    # ### end Alembic commands ###
