"""sub_study_area_id made foreign key

Revision ID: 2e73a0050d5f
Revises: 2c379f2b7db2
Create Date: 2022-02-17 08:44:00.319884

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '2e73a0050d5f'
down_revision = '2c379f2b7db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
