"""renamed accessibility_index

Revision ID: 2ecbc6d64916
Revises: 71eac0e6c8ef
Create Date: 2022-03-12 15:06:36.651821

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ecbc6d64916'
down_revision = '71eac0e6c8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_poi_heatmap', sa.Column('accessibility_indices', sa.ARRAY(sa.Integer()), nullable=False), schema='customer')
    op.drop_column('reached_poi_heatmap', 'accessibility_index', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_poi_heatmap', sa.Column('accessibility_index', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False), schema='customer')
    op.drop_column('reached_poi_heatmap', 'accessibility_indices', schema='customer')
    # ### end Alembic commands ###
