"""added constraints to config

Revision ID: 34ab3518ff84
Revises: 959eb6413158
Create Date: 2022-04-24 08:28:19.462765

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '34ab3518ff84'
down_revision = '959eb6413158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'opportunity_default_config', ['category'], schema='basic')
    op.drop_constraint('opportunity_default_config_group_fkey', 'opportunity_default_config', schema='basic', type_='foreignkey')
    op.create_unique_constraint(None, 'opportunity_study_area_config', ['category', 'study_area_id'], schema='basic')
    op.drop_constraint('opportunity_study_area_config_group_fkey', 'opportunity_study_area_config', schema='basic', type_='foreignkey')
    op.create_unique_constraint(None, 'opportunity_user_config', ['category', 'study_area_id', 'user_id'], schema='customer')
    op.drop_constraint('opportunity_user_config_group_fkey', 'opportunity_user_config', schema='customer', type_='foreignkey')
    op.drop_constraint('opportunity_user_config_data_upload_id_fkey', 'opportunity_user_config', schema='customer', type_='foreignkey')
    op.drop_constraint('opportunity_user_config_user_id_fkey', 'opportunity_user_config', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'opportunity_user_config', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.create_foreign_key(None, 'opportunity_user_config', 'data_upload', ['data_upload_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunity_user_config', schema='customer', type_='foreignkey')
    op.drop_constraint(None, 'opportunity_user_config', schema='customer', type_='foreignkey')
    op.create_foreign_key('opportunity_user_config_user_id_fkey', 'opportunity_user_config', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.create_foreign_key('opportunity_user_config_data_upload_id_fkey', 'opportunity_user_config', 'data_upload', ['data_upload_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.create_foreign_key('opportunity_user_config_group_fkey', 'opportunity_user_config', 'opportunity_group', ['group'], ['group'], source_schema='customer', referent_schema='basic')
    op.drop_constraint(None, 'opportunity_user_config', schema='customer', type_='unique')
    op.create_foreign_key('opportunity_study_area_config_group_fkey', 'opportunity_study_area_config', 'opportunity_group', ['group'], ['group'], source_schema='basic', referent_schema='basic')
    op.drop_constraint(None, 'opportunity_study_area_config', schema='basic', type_='unique')
    op.create_foreign_key('opportunity_default_config_group_fkey', 'opportunity_default_config', 'opportunity_group', ['group'], ['group'], source_schema='basic', referent_schema='basic')
    op.drop_constraint(None, 'opportunity_default_config', schema='basic', type_='unique')
    # ### end Alembic commands ###
