"""make column not nullable

Revision ID: 36878c43943c
Revises: 1410c9e58044
Create Date: 2022-02-13 19:20:58.212484

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36878c43943c'
down_revision = '1410c9e58044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_area', 'default_setting',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_area', 'default_setting',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               schema='basic')
    # ### end Alembic commands ###
