"""Changed from calculation to visualization id

Revision ID: 3a4b84ae169b
Revises: bc65668a0ebc
Create Date: 2022-03-11 09:07:23.133199

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '3a4b84ae169b'
down_revision = 'bc65668a0ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_poi_heatmap', sa.Column('grid_visualization_id', sa.BigInteger(), nullable=False), schema='customer')
    op.drop_constraint('reached_poi_heatmap_grid_calculation_id_fkey', 'reached_poi_heatmap', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'reached_poi_heatmap', 'grid_visualization', ['grid_visualization_id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    op.drop_column('reached_poi_heatmap', 'grid_calculation_id', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_poi_heatmap', sa.Column('grid_calculation_id', sa.BIGINT(), autoincrement=False, nullable=False), schema='customer')
    op.drop_constraint(None, 'reached_poi_heatmap', schema='customer', type_='foreignkey')
    op.create_foreign_key('reached_poi_heatmap_grid_calculation_id_fkey', 'reached_poi_heatmap', 'grid_calculation', ['grid_calculation_id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    op.drop_column('reached_poi_heatmap', 'grid_visualization_id', schema='customer')
    # ### end Alembic commands ###
