"""Added column to refer to data upload

Revision ID: 3d600e6290fd
Revises: 7ecdc1c7b99a
Create Date: 2022-03-11 13:21:19.687907

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '3d600e6290fd'
down_revision = '7ecdc1c7b99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_poi_heatmap', sa.Column('data_upload_id', sa.Integer(), nullable=True), schema='customer')
    op.create_index(op.f('ix_customer_reached_poi_heatmap_data_upload_id'), 'reached_poi_heatmap', ['data_upload_id'], unique=False, schema='customer')
    op.create_foreign_key(None, 'reached_poi_heatmap', 'data_upload', ['data_upload_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reached_poi_heatmap', schema='customer', type_='foreignkey')
    op.drop_index(op.f('ix_customer_reached_poi_heatmap_data_upload_id'), table_name='reached_poi_heatmap', schema='customer')
    op.drop_column('reached_poi_heatmap', 'data_upload_id', schema='customer')
    # ### end Alembic commands ###
