"""added layer source table

Revision ID: 511dcf746333
Revises: e8e45e2881db
Create Date: 2022-03-19 13:13:02.151108

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '511dcf746333'
down_revision = 'e8e45e2881db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layer_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_layer_source_name'), 'layer_source', ['name'], unique=False, schema='customer')
    op.add_column('layer_library', sa.Column('date', sa.DateTime(), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer_library', 'date', schema='customer')
    op.drop_index(op.f('ix_customer_layer_source_name'), table_name='layer_source', schema='customer')
    op.drop_table('layer_source', schema='customer')
    # ### end Alembic commands ###
