"""Removed redundant column

Revision ID: 52a7b98bc5b9
Revises: 23e90887b330
Create Date: 2022-01-31 21:41:05.333291

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52a7b98bc5b9'
down_revision = '23e90887b330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_upload', 'upload_date', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_upload', sa.Column('upload_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True), schema='customer')
    # ### end Alembic commands ###
