"""made edge and node not serial

Revision ID: 548a853f8e9b
Revises: c10d21f8d70c
Create Date: 2022-03-15 20:10:57.798370

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '548a853f8e9b'
down_revision = 'c10d21f8d70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
