"""test

Revision ID: 57abf7756120
Revises: 685e2767a2af
Create Date: 2022-03-09 12:16:54.027613

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '57abf7756120'
down_revision = '685e2767a2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reached_edge_full_heatmap', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=False,
               schema='customer')
    op.alter_column('reached_edge_full_heatmap', 'edge_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='customer')
    op.drop_index('reached_edge_full_heatmap_geom_idx', table_name='reached_edge_full_heatmap', schema='customer')
    op.create_index('idx_reached_edge_full_heatmap_geom', 'reached_edge_full_heatmap', ['geom'], unique=False, schema='customer', postgresql_using='gist')
    op.create_index(op.f('ix_customer_reached_edge_full_heatmap_edge_id'), 'reached_edge_full_heatmap', ['edge_id'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_reached_edge_full_heatmap_scenario_id'), 'reached_edge_full_heatmap', ['scenario_id'], unique=False, schema='customer')
    op.create_foreign_key(None, 'reached_edge_full_heatmap', 'scenario', ['scenario_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.create_foreign_key(None, 'reached_edge_full_heatmap', 'edge', ['edge_id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reached_edge_full_heatmap', schema='customer', type_='foreignkey')
    op.drop_constraint(None, 'reached_edge_full_heatmap', schema='customer', type_='foreignkey')
    op.drop_index(op.f('ix_customer_reached_edge_full_heatmap_scenario_id'), table_name='reached_edge_full_heatmap', schema='customer')
    op.drop_index(op.f('ix_customer_reached_edge_full_heatmap_edge_id'), table_name='reached_edge_full_heatmap', schema='customer')
    op.drop_index('idx_reached_edge_full_heatmap_geom', table_name='reached_edge_full_heatmap', schema='customer', postgresql_using='gist')
    op.create_index('reached_edge_full_heatmap_geom_idx', 'reached_edge_full_heatmap', ['geom'], unique=False, schema='customer')
    op.alter_column('reached_edge_full_heatmap', 'edge_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='customer')
    op.alter_column('reached_edge_full_heatmap', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=True,
               schema='customer')
    # ### end Alembic commands ###
