"""added column for attribute mapping

Revision ID: 5905b5ccb86a
Revises: 141691733561
Create Date: 2023-08-08 19:23:28.812572

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5905b5ccb86a'
down_revision = '141691733561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('attribute_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    op.drop_index('idx_layer_extent', table_name='layer', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_layer_extent', 'layer', ['extent'], unique=False, schema='customer')
    op.drop_column('layer', 'attribute_mapping', schema='customer')
    # ### end Alembic commands ###
