"""Init DB v2

Revision ID: 5bec0eb53799
Revises: 
Create Date: 2023-07-03 07:02:22.870782

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bec0eb53799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Create schema customer 
    op.execute("CREATE SCHEMA IF NOT EXISTS customer;")
    # Create extension uuid-ossp
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_store',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_table('user',
    sa.Column('id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_table('content',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['customer.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_table('scenario',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Text(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['customer.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_table('project',
    sa.Column('content_id', sa.Text(), nullable=False),
    sa.Column('initial_view_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['customer.content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id'),
    schema='customer'
    )
    op.create_table('style',
    sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['customer.content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id'),
    schema='customer'
    )
    op.create_table('layer',
    sa.Column('min_zoom', sa.Integer(), nullable=True),
    sa.Column('max_zoom', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('data_source', sa.Text(), nullable=True),
    sa.Column('data_reference_year', sa.Integer(), nullable=True),
    sa.Column('extent', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('feature_layer_type', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Text(), nullable=False),
    sa.Column('data_store_id', sa.Text(), nullable=True),
    sa.Column('style_id', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Text(), nullable=True),
    sa.Column('legend_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('indicator_type', sa.Text(), nullable=True),
    sa.Column('scenario_id', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opportunities', sa.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['customer.content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_store_id'], ['customer.data_store.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['customer.scenario.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['customer.style.content_id'], ),
    sa.PrimaryKeyConstraint('content_id'),
    schema='customer'
    )
    op.create_table('report',
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['customer.content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['customer.project.content_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id'),
    schema='customer'
    )
    op.create_table('layer_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group', sa.Text(), nullable=True),
    sa.Column('layer_id', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('style_id', sa.Text(), nullable=True),
    sa.Column('active_style_rule', sa.ARRAY(sa.Boolean()), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['customer.layer.content_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['customer.project.content_id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['customer.style.content_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_table('scenario_feature',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Text(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('original_layer_id', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.Text(), nullable=False),
    sa.Column('modification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['original_layer_id'], ['customer.layer.content_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_table('scenario_scenario_feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Text(), nullable=True),
    sa.Column('scenario_feature_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_feature_id'], ['customer.scenario_feature.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['customer.scenario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    # ### end Alembic commands ###


def downgrade():
    # Drop schema customer 
    op.execute("DROP SCHEMA customer;")
    # Create extension uuid-ossp
    op.execute("DROP EXTENSION \"uuid-ossp\";")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_scenario_feature', schema='customer')
    op.drop_table('scenario_feature', schema='customer')
    op.drop_table('layer_project', schema='customer')
    op.drop_table('report', schema='customer')
    op.drop_table('layer', schema='customer')
    op.drop_table('style', schema='customer')
    op.drop_table('project', schema='customer')
    op.drop_table('scenario', schema='customer')
    op.drop_table('content', schema='customer')
    op.drop_table('user', schema='customer')
    op.drop_table('data_store', schema='customer')
    # ### end Alembic commands ###
