"""adjusted reached edges

Revision ID: 685e2767a2af
Revises: 9163a2a385a9
Create Date: 2022-03-09 11:15:40.604402

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '685e2767a2af'
down_revision = '9163a2a385a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reached_edge_artificial_heatmap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edge_id'], ['basic.edge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['customer.scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index('idx_reached_edge_artificial_heatmap_geom', 'reached_edge_artificial_heatmap', ['geom'], unique=False, schema='customer', postgresql_using='gist')
    op.create_index(op.f('ix_customer_reached_edge_artificial_heatmap_edge_id'), 'reached_edge_artificial_heatmap', ['edge_id'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_reached_edge_artificial_heatmap_scenario_id'), 'reached_edge_artificial_heatmap', ['scenario_id'], unique=False, schema='customer')
    op.add_column('reached_edge_heatmap_grid_calculation', sa.Column('start_perc', sa.SmallInteger(), nullable=False), schema='customer')
    op.add_column('reached_edge_heatmap_grid_calculation', sa.Column('end_perc', sa.SmallInteger(), nullable=False), schema='customer')
    op.add_column('reached_edge_heatmap_grid_calculation', sa.Column('edge_type', sa.String(length=1), nullable=False), schema='customer')
    op.drop_column('reached_edge_heatmap_grid_calculation', 'partial_edge', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_edge_heatmap_grid_calculation', sa.Column('partial_edge', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('reached_edge_heatmap_grid_calculation', 'edge_type', schema='customer')
    op.drop_column('reached_edge_heatmap_grid_calculation', 'end_perc', schema='customer')
    op.drop_column('reached_edge_heatmap_grid_calculation', 'start_perc', schema='customer')
    op.drop_index(op.f('ix_customer_reached_edge_artificial_heatmap_scenario_id'), table_name='reached_edge_artificial_heatmap', schema='customer')
    op.drop_index(op.f('ix_customer_reached_edge_artificial_heatmap_edge_id'), table_name='reached_edge_artificial_heatmap', schema='customer')
    op.drop_index('idx_reached_edge_artificial_heatmap_geom', table_name='reached_edge_artificial_heatmap', schema='customer', postgresql_using='gist')
    op.drop_table('reached_edge_artificial_heatmap', schema='customer')
    # ### end Alembic commands ###
