"""added demography for grid visualiation

Revision ID: 7186e5963de4
Revises: bdb8695be3e5
Create Date: 2022-11-11 14:35:46.602604

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7186e5963de4'
down_revision = 'bdb8695be3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid_visualization', sa.Column('demography', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grid_visualization', 'demography', schema='basic')
    # ### end Alembic commands ###
