"""added as accessibility and costs as array

Revision ID: 71eac0e6c8ef
Revises: d488466859f6
Create Date: 2022-03-12 14:35:35.966504

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '71eac0e6c8ef'
down_revision = 'd488466859f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_poi_heatmap', sa.Column('costs', sa.ARRAY(sa.Integer()), nullable=False), schema='customer')
    op.add_column('reached_poi_heatmap', sa.Column('grid_visualization_ids', sa.ARRAY(sa.BigInteger()), nullable=False), schema='customer')
    op.drop_constraint('reached_poi_heatmap_grid_visualization_id_fkey', 'reached_poi_heatmap', schema='customer', type_='foreignkey')
    op.drop_column('reached_poi_heatmap', 'grid_visualization_id', schema='customer')
    op.drop_column('reached_poi_heatmap', 'cost', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_poi_heatmap', sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=False), schema='customer')
    op.add_column('reached_poi_heatmap', sa.Column('grid_visualization_id', sa.BIGINT(), autoincrement=False, nullable=False), schema='customer')
    op.create_foreign_key('reached_poi_heatmap_grid_visualization_id_fkey', 'reached_poi_heatmap', 'grid_visualization', ['grid_visualization_id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    op.drop_column('reached_poi_heatmap', 'grid_visualization_ids', schema='customer')
    op.drop_column('reached_poi_heatmap', 'costs', schema='customer')
    # ### end Alembic commands ###
