"""change is_active default to false

Revision ID: 77ace648b3c7
Revises: f134efcf58fe
Create Date: 2022-04-21 15:44:04.427778

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '77ace648b3c7'
down_revision = 'f134efcf58fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
