"""added further attributes to geostore table

Revision ID: 786395e0b1f4
Revises: 9d4e51a9535c
Create Date: 2022-07-28 13:02:05.366050

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '786395e0b1f4'
down_revision = '9d4e51a9535c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('population', 'test', schema='basic')
    op.add_column('geostore', sa.Column('type', sa.Text(), nullable=True), schema='customer')
    op.add_column('geostore', sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    op.add_column('geostore', sa.Column('attribution', sa.Text(), nullable=True), schema='customer')
    op.alter_column('geostore', 'name',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='customer')
    op.drop_index('ix_customer_geostore_name', table_name='geostore', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_customer_geostore_name', 'geostore', ['name'], unique=False, schema='customer')
    op.alter_column('geostore', 'name',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='customer')
    op.drop_column('geostore', 'attribution', schema='customer')
    op.drop_column('geostore', 'configuration', schema='customer')
    op.drop_column('geostore', 'type', schema='customer')
    op.add_column('population', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True), schema='basic')
    # ### end Alembic commands ###
