"""added new column for study area buffer

Revision ID: 7d1a7713fae2
Revises: 2ecbc6d64916
Create Date: 2022-03-12 15:36:13.352956

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '7d1a7713fae2'
down_revision = '2ecbc6d64916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_area', sa.Column('buffer_geom_heatmap', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True), schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_area', 'buffer_geom_heatmap', schema='basic')
    # ### end Alembic commands ###
