"""Create StaticLayer Model

Revision ID: 7e07e654204b
Revises: 70814d19d9d2
Create Date: 2022-07-05 12:01:46.007154

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '7e07e654204b'
down_revision = '70814d19d9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_layer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=63), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['customer.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name'),
    schema='customer'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_layer', schema='customer')
    # ### end Alembic commands ###
