"""added on delete cascade for user foreign keys

Revision ID: 803ea689f6b8
Revises: f5256a2f45c8
Create Date: 2022-08-11 12:11:44.522079

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '803ea689f6b8'
down_revision = 'f5256a2f45c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('study_area_grid_visualization_grid_visualization_id_fkey', 'study_area_grid_visualization', schema='basic', type_='foreignkey')
    op.drop_constraint('study_area_grid_visualization_study_area_id_fkey', 'study_area_grid_visualization', schema='basic', type_='foreignkey')
    op.create_foreign_key(None, 'study_area_grid_visualization', 'study_area', ['study_area_id'], ['id'], source_schema='basic', referent_schema='basic', ondelete='CASCADE')
    op.create_foreign_key(None, 'study_area_grid_visualization', 'grid_visualization', ['grid_visualization_id'], ['id'], source_schema='basic', referent_schema='basic', ondelete='CASCADE')
    op.drop_constraint('user_role_user_id_fkey', 'user_role', schema='customer', type_='foreignkey')
    op.drop_constraint('user_role_role_id_fkey', 'user_role', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', schema='customer', type_='foreignkey')
    op.drop_constraint(None, 'user_role', schema='customer', type_='foreignkey')
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'role', ['role_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.drop_constraint(None, 'study_area_grid_visualization', schema='basic', type_='foreignkey')
    op.drop_constraint(None, 'study_area_grid_visualization', schema='basic', type_='foreignkey')
    op.create_foreign_key('study_area_grid_visualization_study_area_id_fkey', 'study_area_grid_visualization', 'study_area', ['study_area_id'], ['id'], source_schema='basic', referent_schema='basic')
    op.create_foreign_key('study_area_grid_visualization_grid_visualization_id_fkey', 'study_area_grid_visualization', 'grid_visualization', ['grid_visualization_id'], ['id'], source_schema='basic', referent_schema='basic')
    # ### end Alembic commands ###
