"""Add new POI schema

Revision ID: 829c4e15556f
Revises: 864f72e51788
Create Date: 2022-04-20 11:53:32.160347

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '829c4e15556f'
down_revision = '864f72e51788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group'),
    schema='basic'
    )
    
    op.create_table('poi_default_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.ARRAY(sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['basic.poi_group.group'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='basic'
    )
   
    op.create_table('poi_study_area_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('study_area_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['basic.poi_group.group'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['basic.study_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='basic'
    )
    op.create_table('poi_user_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('study_area_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_upload_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_upload_id'], ['customer.data_upload.id'], ),
    sa.ForeignKeyConstraint(['group'], ['basic.poi_group.group'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['basic.study_area.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['customer.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('poi_user_config', schema='customer')
    op.drop_table('poi_study_area_config', schema='basic')
    op.drop_table('poi_default_config', schema='basic')
    op.drop_table('poi_group', schema='basic')
    # ### end Alembic commands ###
