"""Made not nullable

Revision ID: 83fa7172a5df
Revises: d1c28ac1def7
Create Date: 2022-03-17 22:24:24.315825

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '83fa7172a5df'
down_revision = 'd1c28ac1def7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
