"""added column for special attributes

Revision ID: 85bde75d298b
Revises: e9c6636ddcde
Create Date: 2022-03-19 20:13:49.730671

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85bde75d298b'
down_revision = 'e9c6636ddcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer_library', sa.Column('special_attribute', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer_library', 'special_attribute', schema='customer')
    # ### end Alembic commands ###
