"""Changed projection

Revision ID: 85f55c00ab9f
Revises: bf87de8cbfd4
Create Date: 2022-01-28 09:30:25.217580

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '85f55c00ab9f'
down_revision = 'bf87de8cbfd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('isochrone_edge', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=3857, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True,
               schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('isochrone_edge', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=3857, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True,
               schema='customer')
    # ### end Alembic commands ###
