"""added doc url to layer library

Revision ID: 89df5043b34e
Revises: d0d7dbd36161
Create Date: 2022-09-18 18:30:08.789163

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '89df5043b34e'
down_revision = 'd0d7dbd36161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('layer_library', sa.Column('doc_url', sa.Text(), nullable=True), schema='customer')
    # ### end Alembic commands ###
    print()

def downgrade():
    print()
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('layer_library', 'doc_url', schema='customer')
    # ### end Alembic commands ###
