"""removed not needed columns from node table

Revision ID: 8c1f155cadc8
Revises: fe15a9867004
Create Date: 2022-09-10 12:50:42.700816

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c1f155cadc8'
down_revision = 'fe15a9867004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_basic_node_death_end', table_name='node', schema='basic')
    op.drop_column('node', 'class_ids', schema='basic')
    op.drop_column('node', 'death_end', schema='basic')
    op.drop_column('node', 'cnt', schema='basic')
    op.drop_column('node', 'bicycle', schema='basic')
    op.drop_column('node', 'lit_classified', schema='basic')
    op.drop_column('node', 'wheelchair_classified', schema='basic')
    op.drop_column('node', 'foot', schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('foot', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True), schema='basic')
    op.add_column('node', sa.Column('wheelchair_classified', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True), schema='basic')
    op.add_column('node', sa.Column('lit_classified', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True), schema='basic')
    op.add_column('node', sa.Column('bicycle', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True), schema='basic')
    op.add_column('node', sa.Column('cnt', sa.INTEGER(), autoincrement=False, nullable=True), schema='basic')
    op.add_column('node', sa.Column('death_end', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='basic')
    op.add_column('node', sa.Column('class_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True), schema='basic')
    op.create_index('ix_basic_node_death_end', 'node', ['death_end'], unique=False, schema='basic')
    # ### end Alembic commands ###
