"""updated heatmap tables

Revision ID: 9163a2a385a9
Revises: 49557bfaf7ee
Create Date: 2022-03-08 16:11:16.123586

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '9163a2a385a9'
down_revision = '49557bfaf7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reached_edge_heatmap_grid_calculation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('start_cost', sa.SmallInteger(), nullable=False),
    sa.Column('end_cost', sa.SmallInteger(), nullable=False),
    sa.Column('grid_calculation_id', sa.BigInteger(), nullable=False),
    sa.Column('reached_edge_heatmap_id', sa.Integer(), nullable=False),
    sa.Column('partial_edge', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grid_calculation_id'], ['basic.grid_calculation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_reached_edge_heatmap_grid_calculation_grid_calculation_id'), 'reached_edge_heatmap_grid_calculation', ['grid_calculation_id'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_reached_edge_heatmap_grid_calculation_reached_edge_heatmap_id'), 'reached_edge_heatmap_grid_calculation', ['reached_edge_heatmap_id'], unique=False, schema='customer')
    op.create_table('reached_poi_heatmap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grid_calculation_id', sa.BigInteger(), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid_calculation_id'], ['basic.grid_calculation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poi_id'], ['basic.poi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['customer.scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_reached_poi_heatmap_scenario_id'), 'reached_poi_heatmap', ['scenario_id'], unique=False, schema='customer')
    op.create_table('reached_poi_heatmap_accessibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reached_poi_heatmap_id', sa.Integer(), nullable=False),
    sa.Column('sensitivity', sa.Integer(), nullable=False),
    sa.Column('accessibility_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reached_poi_heatmap_id'], ['customer.reached_poi_heatmap.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_table('reached_edge_full_heatmap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edge_id'], ['basic.edge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['customer.scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_reached_edge_full_heatmap_edge_id'), 'reached_edge_full_heatmap', ['edge_id'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_reached_edge_full_heatmap_scenario_id'), 'reached_edge_full_heatmap', ['scenario_id'], unique=False, schema='customer')
    op.create_table('reached_edge_partial_heatmap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_perc', sa.Float(precision=53), nullable=False),
    sa.Column('end_perc', sa.Float(precision=53), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('partial_edge', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['basic.edge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['customer.scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index('idx_reached_edge_full_heatmap_geom', 'reached_edge_partial_heatmap', ['geom'], unique=False, schema='customer', postgresql_using='gist')
    op.create_index('idx_reached_edge_partial_heatmap_geom', 'reached_edge_partial_heatmap', ['geom'], unique=False, schema='customer', postgresql_using='gist')
    op.create_index(op.f('ix_customer_reached_edge_partial_heatmap_edge_id'), 'reached_edge_partial_heatmap', ['edge_id'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_reached_edge_partial_heatmap_scenario_id'), 'reached_edge_partial_heatmap', ['scenario_id'], unique=False, schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_reached_edge_partial_heatmap_scenario_id'), table_name='reached_edge_partial_heatmap', schema='customer')
    op.drop_index(op.f('ix_customer_reached_edge_partial_heatmap_edge_id'), table_name='reached_edge_partial_heatmap', schema='customer')
    op.drop_index('idx_reached_edge_partial_heatmap_geom', table_name='reached_edge_partial_heatmap', schema='customer', postgresql_using='gist')
    op.drop_index('idx_reached_edge_full_heatmap_geom', table_name='reached_edge_partial_heatmap', schema='customer', postgresql_using='gist')
    op.drop_table('reached_edge_partial_heatmap', schema='customer')
    op.drop_index(op.f('ix_customer_reached_edge_full_heatmap_scenario_id'), table_name='reached_edge_full_heatmap', schema='customer')
    op.drop_index(op.f('ix_customer_reached_edge_full_heatmap_edge_id'), table_name='reached_edge_full_heatmap', schema='customer')
    op.drop_table('reached_edge_full_heatmap', schema='customer')
    op.drop_table('reached_poi_heatmap_accessibility', schema='customer')
    op.drop_index(op.f('ix_customer_reached_poi_heatmap_scenario_id'), table_name='reached_poi_heatmap', schema='customer')
    op.drop_table('reached_poi_heatmap', schema='customer')
    op.drop_index(op.f('ix_customer_reached_edge_heatmap_grid_calculation_reached_edge_heatmap_id'), table_name='reached_edge_heatmap_grid_calculation', schema='customer')
    op.drop_index(op.f('ix_customer_reached_edge_heatmap_grid_calculation_grid_calculation_id'), table_name='reached_edge_heatmap_grid_calculation', schema='customer')
    op.drop_table('reached_edge_heatmap_grid_calculation', schema='customer')
    # ### end Alembic commands ###
