"""fixing traveltime matrix walking

Revision ID: 9428f5fa2353
Revises: 7186e5963de4
Create Date: 2022-11-26 12:35:13.052990

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '9428f5fa2353'
down_revision = '7186e5963de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'traveltime_matrix_walking', 'grid_calculation', ['grid_calculation_id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traveltime_matrix_walking', schema='customer', type_='foreignkey')
    # ### end Alembic commands ###
