"""changed poi config to opportunity

Revision ID: 959eb6413158
Revises: 16aa38de4035
Create Date: 2022-04-22 14:01:12.031540

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '959eb6413158'
down_revision = '16aa38de4035'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('poi_user_config', schema='customer')
    op.drop_table('poi_study_area_config', schema='basic')
    op.drop_table('poi_default_config', schema='basic')
    op.drop_table('poi_group', schema='basic')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group'),
    schema='basic'
    )
    op.create_table('opportunity_default_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('sensitivity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['basic.opportunity_group.group'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='basic'
    )

    op.create_table('opportunity_study_area_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('sensitivity', sa.Integer(), nullable=True),
    sa.Column('study_area_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['basic.opportunity_group.group'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['basic.study_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='basic'
    )
    op.create_table('opportunity_user_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('sensitivity', sa.Integer(), nullable=True),
    sa.Column('study_area_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_upload_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_upload_id'], ['customer.data_upload.id'], ),
    sa.ForeignKeyConstraint(['group'], ['basic.opportunity_group.group'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['basic.study_area.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['customer.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_user_config', schema='customer')
    op.drop_table('opportunity_study_area_config', schema='basic')
    op.drop_table('opportunity_default_config', schema='basic')
    op.drop_table('opportunity_group', schema='basic')
    # ### end Alembic commands ###
