"""changed type foreign key and added unique constraint

Revision ID: 97628bcd480b
Revises: 2ac47db804a1
Create Date: 2022-03-19 12:10:52.153578

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '97628bcd480b'
down_revision = '2ac47db804a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'layer_library', ['name'], schema='customer')
    op.drop_constraint('layer_library_style_library_id_fkey', 'layer_library', schema='customer', type_='foreignkey')
    op.drop_column('layer_library', 'style_library_id', schema='customer')
    op.create_unique_constraint(None, 'style_library', ['name'], schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'style_library', schema='customer', type_='unique')
    op.add_column('layer_library', sa.Column('style_library_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='customer')
    op.create_foreign_key('layer_library_style_library_id_fkey', 'layer_library', 'style_library', ['style_library_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.drop_constraint(None, 'layer_library', schema='customer', type_='unique')
    # ### end Alembic commands ###
