"""renamed building

Revision ID: 986bbb0db4d4
Revises: 25d7b7610160
Create Date: 2022-03-15 12:53:04.532586

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '986bbb0db4d4'
down_revision = '25d7b7610160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('building_type', sa.Text(), nullable=True), schema='basic')
    op.drop_column('building', 'building', schema='basic')
    op.add_column('building_modified', sa.Column('building_type', sa.Text(), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building_modified', 'building_type', schema='customer')
    op.add_column('building', sa.Column('building', sa.TEXT(), autoincrement=False, nullable=True), schema='basic')
    op.drop_column('building', 'building_type', schema='basic')
    # ### end Alembic commands ###
