"""Updating config tables foreign key

Revision ID: 99c36dc4c2ff
Revises: a720adfaab14
Create Date: 2022-04-26 08:53:29.062988

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '99c36dc4c2ff'
down_revision = 'a720adfaab14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_default_config', sa.Column('opportunity_group_id', sa.Integer(), nullable=False), schema='basic')
    op.drop_column('opportunity_default_config', 'group_id', schema='basic')
    op.add_column('opportunity_study_area_config', sa.Column('opportunity_group_id', sa.Integer(), nullable=False), schema='basic')
    op.drop_column('opportunity_study_area_config', 'group_id', schema='basic')
    op.add_column('opportunity_user_config', sa.Column('opportunity_group_id', sa.Integer(), nullable=False), schema='customer')
    op.drop_column('opportunity_user_config', 'group_id', schema='customer')
    op.create_foreign_key(None, 'opportunity_default_config', 'opportunity_group', ['opportunity_group_id'], ['id'], source_schema='basic', referent_schema='basic')
    op.create_foreign_key(None, 'opportunity_study_area_config', 'opportunity_group', ['opportunity_group_id'], ['id'], source_schema='basic', referent_schema='basic')
    op.create_foreign_key(None, 'opportunity_user_config', 'opportunity_group', ['opportunity_group_id'], ['id'], source_schema='customer', referent_schema='basic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_user_config', sa.Column('group_id', sa.TEXT(), autoincrement=False, nullable=False), schema='customer')
    op.drop_column('opportunity_user_config', 'opportunity_group_id', schema='customer')
    op.add_column('opportunity_study_area_config', sa.Column('group_id', sa.TEXT(), autoincrement=False, nullable=False), schema='basic')
    op.drop_column('opportunity_study_area_config', 'opportunity_group_id', schema='basic')
    op.add_column('opportunity_default_config', sa.Column('group_id', sa.TEXT(), autoincrement=False, nullable=False), schema='basic')
    op.drop_column('opportunity_default_config', 'opportunity_group_id', schema='basic')
    # ### end Alembic commands ###
