"""added column multiple entrance

Revision ID: 9a71c3d6d26c
Revises: 34ab3518ff84
Create Date: 2022-04-24 09:55:01.719098

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '9a71c3d6d26c'
down_revision = '34ab3518ff84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_default_config', sa.Column('multiple_entrace', sa.Boolean(), nullable=True), schema='basic')
    op.add_column('opportunity_study_area_config', sa.Column('multiple_entrace', sa.Boolean(), nullable=True), schema='basic')
    op.add_column('opportunity_user_config', sa.Column('multiple_entrace', sa.Boolean(), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_user_config', 'multiple_entrace', schema='customer')
    op.drop_column('opportunity_study_area_config', 'multiple_entrace', schema='basic')
    op.drop_column('opportunity_default_config', 'multiple_entrace', schema='basic')
    # ### end Alembic commands ###
