"""Changed to array

Revision ID: 9ad7c69af4df
Revises: cf653cf1275c
Create Date: 2022-03-10 20:13:09.477711

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '9ad7c69af4df'
down_revision = 'cf653cf1275c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reached_poi_heatmap', 'accessibility_index', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_poi_heatmap', sa.Column('accessibility_index', sa.INTEGER(), autoincrement=False, nullable=False), schema='customer')
    # ### end Alembic commands ###
