"""added geostore tables

Revision ID: 9d4e51a9535c
Revises: 70814d19d9d2
Create Date: 2022-07-27 09:07:43.823152

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '9d4e51a9535c'
down_revision = '70814d19d9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geostore',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_geostore_name'), 'geostore', ['name'], unique=False, schema='customer')
    op.create_table('study_area_geostore',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_area_id', sa.Integer(), nullable=False),
    sa.Column('geostore_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geostore_id'], ['customer.geostore.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['basic.study_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_study_area_geostore_geostore_id'), 'study_area_geostore', ['geostore_id'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_study_area_geostore_study_area_id'), 'study_area_geostore', ['study_area_id'], unique=False, schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_study_area_geostore_study_area_id'), table_name='study_area_geostore', schema='customer')
    op.drop_index(op.f('ix_customer_study_area_geostore_geostore_id'), table_name='study_area_geostore', schema='customer')
    op.drop_table('study_area_geostore', schema='customer')
    op.drop_index(op.f('ix_customer_geostore_name'), table_name='geostore', schema='customer')
    op.drop_table('geostore', schema='customer')
    # ### end Alembic commands ###
