"""changed foreign key to group id

Revision ID: a720adfaab14
Revises: 1c1cd1e80930
Create Date: 2022-04-26 08:22:25.395319

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'a720adfaab14'
down_revision = '1c1cd1e80930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_default_config', sa.Column('group_id', sa.Text(), nullable=False), schema='basic')
    op.drop_column('opportunity_default_config', 'group', schema='basic')
    op.add_column('opportunity_study_area_config', sa.Column('group_id', sa.Text(), nullable=False), schema='basic')
    op.drop_column('opportunity_study_area_config', 'group', schema='basic')
    op.add_column('opportunity_user_config', sa.Column('group_id', sa.Text(), nullable=False), schema='customer')
    op.drop_column('opportunity_user_config', 'group', schema='customer')
    op.create_foreign_key(None, 'opportunity_user_config', 'user', ['user_id'], ['id'], source_schema='basic', referent_schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_user_config', sa.Column('group', sa.TEXT(), autoincrement=False, nullable=False), schema='customer')
    op.drop_column('opportunity_user_config', 'group_id', schema='customer')
    op.add_column('opportunity_study_area_config', sa.Column('group', sa.TEXT(), autoincrement=False, nullable=False), schema='basic')
    op.drop_column('opportunity_study_area_config', 'group_id', schema='basic')
    op.add_column('opportunity_default_config', sa.Column('group', sa.TEXT(), autoincrement=False, nullable=False), schema='basic')
    op.drop_column('opportunity_default_config', 'group_id', schema='basic')
    # ### end Alembic commands ###
