"""Added end and start perc

Revision ID: ac1a55013c59
Revises: f52751aff400
Create Date: 2022-01-27 16:52:34.629962

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac1a55013c59'
down_revision = 'f52751aff400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('isochrone_edge', sa.Column('start_perc', sa.Float(precision=53), nullable=True), schema='customer')
    op.add_column('isochrone_edge', sa.Column('end_perc', sa.Float(precision=53), nullable=True), schema='customer')
    op.alter_column('isochrone_edge', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='customer')
    op.alter_column('isochrone_edge', 'start_cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='customer')
    op.alter_column('isochrone_edge', 'end_cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('isochrone_edge', 'end_cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               schema='customer')
    op.alter_column('isochrone_edge', 'start_cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               schema='customer')
    op.alter_column('isochrone_edge', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               schema='customer')
    op.drop_column('isochrone_edge', 'end_perc', schema='customer')
    op.drop_column('isochrone_edge', 'start_perc', schema='customer')
    # ### end Alembic commands ###
