"""Changed data type deleted pois

Revision ID: b6ce6de82807
Revises: 52a7b98bc5b9
Create Date: 2022-02-02 14:10:41.850333

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6ce6de82807'
down_revision = '52a7b98bc5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario', 'deleted_pois',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"),
               schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario', 'deleted_pois',
               existing_type=sa.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"),
               schema='customer')
    # ### end Alembic commands ###
