"""empty message

Revision ID: bc0b17b69886
Revises: 9428f5fa2353
Create Date: 2023-03-19 17:25:43.766088

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'bc0b17b69886'
down_revision = '9428f5fa2353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveltime_matrix_walking', schema='customer')
    op.drop_table('study_area_grid_visualization', schema='basic')
    op.drop_table('reached_edge_full_heatmap', schema='customer')
    op.drop_table('reached_edge_heatmap_grid_calculation', schema='customer')
    op.drop_table('reached_poi_heatmap', schema='customer')
    op.drop_table('grid_calculation', schema='basic')
    op.drop_table('grid_visualization', schema='basic')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
