"""Changed to array

Revision ID: bc65668a0ebc
Revises: 9ad7c69af4df
Create Date: 2022-03-10 20:13:48.698167

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'bc65668a0ebc'
down_revision = '9ad7c69af4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reached_poi_heatmap', sa.Column('accessibility_index', sa.ARRAY(sa.Integer()), nullable=False), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reached_poi_heatmap', 'accessibility_index', schema='customer')
    # ### end Alembic commands ###
