"""fixed matrix schema

Revision ID: bdb8695be3e5
Revises: ee689704a105
Create Date: 2022-10-20 20:34:46.721126

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdb8695be3e5'
down_revision = 'ee689704a105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traveltime_matrix_walking', sa.Column('north', sa.Integer(), nullable=True), schema='customer')
    op.add_column('traveltime_matrix_walking', sa.Column('west', sa.Integer(), nullable=True), schema='customer')
    op.drop_column('traveltime_matrix_walking', 'northwest', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traveltime_matrix_walking', sa.Column('northwest', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('traveltime_matrix_walking', 'west', schema='customer')
    op.drop_column('traveltime_matrix_walking', 'north', schema='customer')
    # ### end Alembic commands ###
