"""Made column length_3857 not nullable

Revision ID: bf178b4433dc
Revises: 199ee7bfd0ef
Create Date: 2022-01-26 15:49:19.878583

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf178b4433dc'
down_revision = '199ee7bfd0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edge', 'length_3857',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edge', 'length_3857',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               schema='basic')
    # ### end Alembic commands ###
