"""Added geometry column

Revision ID: bf87de8cbfd4
Revises: ac1a55013c59
Create Date: 2022-01-28 09:12:50.086981

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bf87de8cbfd4'
down_revision = 'ac1a55013c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('isochrone_edge', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('isochrone_edge', 'geom', schema='customer')
    # ### end Alembic commands ###
