"""Removed column and changed constraint

Revision ID: c1b80b3c0834
Revises: 0b4df0916d2e
Create Date: 2022-03-11 17:03:16.869349

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'c1b80b3c0834'
down_revision = '0b4df0916d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poi_modified', 'uid',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='customer')
    op.drop_index('ix_customer_poi_modified_table_name', table_name='poi_modified', schema='customer')
    op.drop_column('poi_modified', 'table_name', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi_modified', sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=False), schema='customer')
    op.create_index('ix_customer_poi_modified_table_name', 'poi_modified', ['table_name'], unique=False, schema='customer')
    op.alter_column('poi_modified', 'uid',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='customer')
    # ### end Alembic commands ###
