"""removed isochrone feature table

Revision ID: c82e304d9689
Revises: 8c1f155cadc8
Create Date: 2022-09-10 13:20:46.598804

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'c82e304d9689'
down_revision = '8c1f155cadc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('isochrone_feature', schema='customer')
    op.drop_table('region_r5', schema='basic')
    pass
    # ### end Alembic commands ###


def downgrade():
    op.create_table('isochrone_feature', schema='customer')
    op.create_table('region_r5', schema='basic')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
