"""Removed foreign key

Revision ID: c8a4691be513
Revises: e568f9294ea4
Create Date: 2022-03-10 12:49:53.031237

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'c8a4691be513'
down_revision = 'e568f9294ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reached_edge_full_heatmap_edge_id_fkey', 'reached_edge_full_heatmap', schema='customer', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reached_edge_full_heatmap_edge_id_fkey', 'reached_edge_full_heatmap', 'edge', ['edge_id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    # ### end Alembic commands ###
