"""Changed to array

Revision ID: cf653cf1275c
Revises: 061d24af05c8
Create Date: 2022-03-10 20:11:39.526814

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'cf653cf1275c'
down_revision = '061d24af05c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
