"""Added max number scenarios and default values

Revision ID: d1c28ac1def7
Revises: e55924154808
Create Date: 2022-03-17 22:21:03.522489

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'd1c28ac1def7'
down_revision = 'e55924154808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('limit_scenarios', sa.Integer(), nullable=True), schema='customer')
    op.alter_column('user', 'storage',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'storage',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='customer')
    op.drop_column('user', 'limit_scenarios', schema='customer')
    # ### end Alembic commands ###
