"""add on delete cascade to link

Revision ID: d260d4b2c436
Revises: 2b369bf7669a
Create Date: 2023-09-02 15:28:21.805699

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'd260d4b2c436'
down_revision = '2b369bf7669a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_project_user_id_fkey', 'user_project', schema='customer', type_='foreignkey')
    op.drop_constraint('user_project_project_id_fkey', 'user_project', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'user_project', 'project', ['project_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_project', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_project', schema='customer', type_='foreignkey')
    op.drop_constraint(None, 'user_project', schema='customer', type_='foreignkey')
    op.create_foreign_key('user_project_project_id_fkey', 'user_project', 'project', ['project_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.create_foreign_key('user_project_user_id_fkey', 'user_project', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer')
    # ### end Alembic commands ###
