"""Added uid constraint again

Revision ID: d488466859f6
Revises: c1b80b3c0834
Create Date: 2022-03-11 18:06:56.024094

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'd488466859f6'
down_revision = 'c1b80b3c0834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poi_modified', 'uid',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poi_modified', 'uid',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='customer')
    # ### end Alembic commands ###
