"""added table to store analysis request

Revision ID: d903c3d3ec87
Revises: 5bec0eb53799
Create Date: 2023-07-04 06:54:06.643627

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd903c3d3ec87'
down_revision = '5bec0eb53799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_request',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Text(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('layer_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['customer.layer.content_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_analysis_request_layer_id'), 'analysis_request', ['layer_id'], unique=False, schema='customer')
    op.drop_index('idx_layer_extent', table_name='layer', schema='customer')
    op.drop_column('layer_project', 'active_style_rule', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer_project', sa.Column('active_style_rule', postgresql.ARRAY(sa.BOOLEAN()), autoincrement=False, nullable=True), schema='customer')
    op.create_index('idx_layer_extent', 'layer', ['extent'], unique=False, schema='customer')
    op.drop_index(op.f('ix_customer_analysis_request_layer_id'), table_name='analysis_request', schema='customer')
    op.drop_table('analysis_request', schema='customer')
    # ### end Alembic commands ###
