"""Remove foreign key edge

Revision ID: da770d01fcb8
Revises: 57abf7756120
Create Date: 2022-03-09 12:34:59.541768

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'da770d01fcb8'
down_revision = '57abf7756120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reached_edge_artificial_heatmap_edge_id_fkey', 'reached_edge_artificial_heatmap', schema='customer', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reached_edge_artificial_heatmap_edge_id_fkey', 'reached_edge_artificial_heatmap', 'edge', ['edge_id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    # ### end Alembic commands ###
