"""added library tables

Revision ID: db471c586acc
Revises: 1e5d9e0f1e7b
Create Date: 2022-03-18 22:58:54.253213

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db471c586acc'
down_revision = '1e5d9e0f1e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_style_library_name'), 'style_library', ['name'], unique=False, schema='customer')
    op.create_table('layer_library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('map_attribution', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_library_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['style_library_id'], ['customer.style_library.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_layer_library_name'), 'layer_library', ['name'], unique=False, schema='customer')
    op.create_index(op.f('ix_customer_layer_library_type'), 'layer_library', ['type'], unique=False, schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_layer_library_type'), table_name='layer_library', schema='customer')
    op.drop_index(op.f('ix_customer_layer_library_name'), table_name='layer_library', schema='customer')
    op.drop_table('layer_library', schema='customer')
    op.drop_index(op.f('ix_customer_style_library_name'), table_name='style_library', schema='customer')
    op.drop_table('style_library', schema='customer')
    # ### end Alembic commands ###
