"""added study area column to user_customization

Revision ID: e1d37f2ad634
Revises: 1ad086c93866
Create Date: 2022-02-22 15:24:02.173032

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'e1d37f2ad634'
down_revision = '1ad086c93866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_customization', sa.Column('study_area_id', sa.Integer(), nullable=False), schema='customer')
    op.create_foreign_key(None, 'user_customization', 'study_area', ['study_area_id'], ['id'], source_schema='customer', referent_schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_customization', schema='customer', type_='foreignkey')
    op.drop_column('user_customization', 'study_area_id', schema='customer')
    # ### end Alembic commands ###
