"""added population column to building

Revision ID: e55924154808
Revises: 548a853f8e9b
Create Date: 2022-03-17 12:44:56.681906

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'e55924154808'
down_revision = '548a853f8e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_modified', sa.Column('population', sa.Float(precision=53), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building_modified', 'population', schema='customer')
    # ### end Alembic commands ###
