"""remove foreign key

Revision ID: e5cb614aafa9
Revises: 2e73a0050d5f
Create Date: 2022-02-17 18:05:29.718761

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'e5cb614aafa9'
down_revision = '2e73a0050d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_study_area_id', sa.Integer(), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_study_area_id', schema='customer')
    # ### end Alembic commands ###
