"""added condition on update cascade

Revision ID: e8e45e2881db
Revises: 05a8620ed15d
Create Date: 2022-03-19 13:03:05.208164

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'e8e45e2881db'
down_revision = '05a8620ed15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('layer_library_style_library_name_fkey', 'layer_library', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'layer_library', 'style_library', ['style_library_name'], ['name'], source_schema='customer', referent_schema='customer', onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'layer_library', schema='customer', type_='foreignkey')
    op.create_foreign_key('layer_library_style_library_name_fkey', 'layer_library', 'style_library', ['style_library_name'], ['name'], source_schema='customer', referent_schema='customer')
    # ### end Alembic commands ###
