"""changed date to text

Revision ID: e9c6636ddcde
Revises: 86c8016f081e
Create Date: 2022-03-19 15:28:05.143611

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9c6636ddcde'
down_revision = '86c8016f081e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layer_library', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Text(),
               existing_nullable=True,
               schema='customer')
    op.alter_column('layer_library', 'date_1',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Text(),
               existing_nullable=True,
               schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layer_library', 'date_1',
               existing_type=sa.Text(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='customer')
    op.alter_column('layer_library', 'date',
               existing_type=sa.Text(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='customer')
    # ### end Alembic commands ###
