"""empty message

Revision ID: eda574247c2b
Revises: bc0b17b69886
Create Date: 2023-03-20 08:54:03.586229

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'eda574247c2b'
down_revision = 'bc0b17b69886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('building_modified_building_id_fkey', 'building_modified', schema='customer', type_='foreignkey')
    op.drop_constraint('way_modified_way_id_fkey', 'way_modified', schema='customer', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('way_modified_way_id_fkey', 'way_modified', 'edge', ['way_id'], ['id'], source_schema='customer', referent_schema='basic')
    op.create_foreign_key('building_modified_building_id_fkey', 'building_modified', 'building', ['building_id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    # ### end Alembic commands ###
