"""Added traveltimematrix table

Revision ID: ee689704a105
Revises: 89df5043b34e
Create Date: 2022-10-20 12:33:21.179822

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'ee689704a105'
down_revision = '89df5043b34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveltime_matrix_walking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grid_calculation_id', sa.BigInteger(), nullable=False),
    sa.Column('northwest', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('heigth', sa.SmallInteger(), nullable=True),
    sa.Column('width', sa.SmallInteger(), nullable=True),
    sa.Column('costs', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['grid_calculation_id'], ['basic.grid_calculation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_traveltime_matrix_walking_grid_calculation_id'), 'traveltime_matrix_walking', ['grid_calculation_id'], unique=True, schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_traveltime_matrix_walking_grid_calculation_id'), table_name='traveltime_matrix_walking', schema='customer')
    op.drop_table('traveltime_matrix_walking', schema='customer')
    # ### end Alembic commands ###
