"""changed column name

Revision ID: eebe1f124bc6
Revises: 85bde75d298b
Create Date: 2022-03-19 21:51:03.064555

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eebe1f124bc6'
down_revision = '85bde75d298b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style_library', sa.Column('translation', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    op.drop_column('style_library', 'translations', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style_library', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('style_library', 'translation', schema='customer')
    # ### end Alembic commands ###
