"""geostores name unique and on delete cascade

Revision ID: f5256a2f45c8
Revises: 93a4df3f3b10
Create Date: 2022-08-11 11:49:55.055582

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'f5256a2f45c8'
down_revision = '93a4df3f3b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'geostore', ['name'], schema='customer')
    op.drop_constraint('study_area_geostore_geostore_id_fkey', 'study_area_geostore', schema='customer', type_='foreignkey')
    op.drop_constraint('study_area_geostore_study_area_id_fkey', 'study_area_geostore', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'study_area_geostore', 'study_area', ['study_area_id'], ['id'], source_schema='customer', referent_schema='basic', ondelete='CASCADE')
    op.create_foreign_key(None, 'study_area_geostore', 'geostore', ['geostore_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_area_geostore', schema='customer', type_='foreignkey')
    op.drop_constraint(None, 'study_area_geostore', schema='customer', type_='foreignkey')
    op.create_foreign_key('study_area_geostore_study_area_id_fkey', 'study_area_geostore', 'study_area', ['study_area_id'], ['id'], source_schema='customer', referent_schema='basic')
    op.create_foreign_key('study_area_geostore_geostore_id_fkey', 'study_area_geostore', 'geostore', ['geostore_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.drop_constraint(None, 'geostore', schema='customer', type_='unique')
    # ### end Alembic commands ###
