"""added icon and color to poi group

Revision ID: fa649dc2dca0
Revises: 910f067bbf0b
Create Date: 2022-04-22 08:24:57.697553

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'fa649dc2dca0'
down_revision = '910f067bbf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi_group', sa.Column('icon', sa.Text(), nullable=False), schema='basic')
    op.add_column('poi_group', sa.Column('color', sa.ARRAY(sa.Text()), nullable=False), schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poi_group', 'color', schema='basic')
    op.drop_column('poi_group', 'icon', schema='basic')
    # ### end Alembic commands ###
