"""added edge id

Revision ID: fb86d4ee2936
Revises: 83fa7172a5df
Create Date: 2022-03-18 17:16:59.436684

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'fb86d4ee2936'
down_revision = '83fa7172a5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('way_modified', sa.Column('way_id', sa.Integer(), nullable=True), schema='customer')
    op.drop_index('ix_customer_way_modified_edge_id', table_name='way_modified', schema='customer')
    op.create_index(op.f('ix_customer_way_modified_way_id'), 'way_modified', ['way_id'], unique=False, schema='customer')
    op.drop_constraint('way_modified_edge_id_fkey', 'way_modified', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'way_modified', 'edge', ['way_id'], ['id'], source_schema='customer', referent_schema='basic')
    op.drop_column('way_modified', 'edge_id', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('way_modified', sa.Column('edge_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='customer')
    op.drop_constraint(None, 'way_modified', schema='customer', type_='foreignkey')
    op.create_foreign_key('way_modified_edge_id_fkey', 'way_modified', 'edge', ['edge_id'], ['id'], source_schema='customer', referent_schema='basic')
    op.drop_index(op.f('ix_customer_way_modified_way_id'), table_name='way_modified', schema='customer')
    op.create_index('ix_customer_way_modified_edge_id', 'way_modified', ['edge_id'], unique=False, schema='customer')
    op.drop_column('way_modified', 'way_id', schema='customer')
    # ### end Alembic commands ###
