"""added region r5 table

Revision ID: fe15a9867004
Revises: 803ea689f6b8
Create Date: 2022-08-27 13:41:18.998986

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'fe15a9867004'
down_revision = '803ea689f6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_r5',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('reference_dates', sa.ARRAY(sa.DateTime()), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('buffer_geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='basic'
    )
    op.create_index('idx_region_r5_buffer_geom', 'region_r5', ['buffer_geom'], unique=False, schema='basic', postgresql_using='gist')
    op.create_index('idx_region_r5_geom', 'region_r5', ['geom'], unique=False, schema='basic', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_region_r5_geom', table_name='region_r5', schema='basic', postgresql_using='gist')
    op.drop_index('idx_region_r5_buffer_geom', table_name='region_r5', schema='basic', postgresql_using='gist')
    op.drop_table('region_r5', schema='basic')
    # ### end Alembic commands ###
