@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_LEFT_RIGHT()
title Top Level Context Diagram (C4 Model)

SHOW_PERSON_OUTLINE()
Person(personAlias, "User", "A user of GOAT application")
System(goatSystem, "GOAT System", "Allows users to conduct accessibility analysis, evaluate scenarios and visualize geospatial data")
System_Ext(r5System, "R5 System", "Public transport routing engine")

Rel(personAlias, goatSystem, "Uses", "HTTPS")
Rel(goatSystem, r5System, "Gets travel-time calculations", "HTTP")

@enduml