@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/postgresql.puml
!include FONTAWESOME/train.puml

' title R5 Data processing diagram

SHOW_PERSON_OUTLINE()
Boundary(outputData, "Isochrone Data", "") { 
ContainerDb(db, "Database", "PostgreSQL", "Holds points of interest and population data", $sprite="postgresql")    
ContainerDb(r5Network, "Transit Network", ".dat", "Holds the routable transit network for R5", $sprite="train")    
}
Boundary(inputRaw, "Raw Data", "Input") { 
ContainerDb_Ext(gtfsData, "GTFS", ".zip", "A set of CSV files inside a .zip archive")
ContainerDb_Ext(osmData, "OSM", ".pbf", "A binary file which defines the street layer of the baseline transport network")
}
Component(r5Engine, "Processing", "", "Process GTFS (.zip) and OSM (.pbf) by running a series of algorithms. The output is routable transit network for R5 system")
Component(isochroneCalculation, "Isochrone Calculation", "Component", "")


Rel(r5Engine, inputRaw, "Reads")
Rel(r5Engine, r5Network, "Outputs")

Rel(isochroneCalculation, outputData, "Uses")

SHOW_LEGEND()
@enduml