########################################################################################
# "client-cache-build" composite action for client build                               #
#--------------------------------------------------------------------------------------#
#                                                                                      #
# Usage in workflows steps:                                                            #
#                                                                                      #
#      - name: 🏗️ Monorepo build                                                       #
#        uses: ./.github/actions/client-cache-build                                    #
#        with:                                                                         #
#          cwd: ${{ github.workspace }}/apps/web  # (default = '.')                    #
########################################################################################

name: "Cache production build binaries"
description: "Cache or restore if necessary"
author: "Plan4Better GmbH"

inputs:
  cwd:
    description: "Changes node's process.cwd() if the project is not located on the root. Default to process.cwd()"
    required: false
    default: '.'
  node_version:
    description: "Node version to use"
    required: false
    default: v18.x

runs:
  using: "composite"
  steps:
    - name: Cache production build
      uses: actions/cache@v3
      id: cache-build
      env:
        cache-name: prod-build
        key-1: ${{ inputs.node_version }}-${{ hashFiles('${{ inputs.cwd }}/pnpm-lock.yaml') }}
        key-2: ${{ hashFiles('${{ inputs.cwd }}/apps/**/**.[jt]s', '${{ inputs.cwd }}/apps/**/**.[jt]sx', '${{ inputs.cwd }}/packages/**/**.[jt]s', '${{ inputs.cwd }}/packages/**/**.[jt]sx', '!**/node_modules') }}
        key-3: ${{ github.event.pull_request.number || github.ref }}
        # Ensures production-build.yml will always be fresh
        key-4: ${{ github.sha }}
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next
          **/.turbo/**
          **/dist/**
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-${{ env.key-3 }}-${{ env.key-4 }}
        
    - run: pnpm run build
      working-directory: ${{ inputs.cwd }}
      if: steps.cache-build.outputs.cache-hit != 'true'
      shell: bash