//import $ from 'jquery';
//import "./js/index_functions"
import "./js/secrets"
import "./js/tooltip"
import "./js/variables"
import "./js/isochrones"
import "./js/style"
import "./js/basemaps"
import "./js/interaction"
import "./js/other_layers"
import "./js/data_preparation"
