@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include FONTAWESOME/users.puml
!include FONTAWESOME/vuejs.puml
!include FONTAWESOME/python.puml
!include FONTAWESOME/file.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/mongodb.puml
!include DEVICONS/java.puml
!include DEVICONS/javascript.puml
!include DEVICONS/react.puml

title Container Diagram (C4 Model)

SHOW_PERSON_OUTLINE()
Person(user, "User", "A user of the GOAT platform", $sprite="users")

System_Boundary(c1, "Web Application"){
    Container(client, "Client", "React.js & Next.js", "Frontend of the GOAT application", $sprite="react")
}

System_Boundary(a1, "Authentication"){
    Container(auth, "Keycloak API", "Keycloak", "Handles authentication for GOAT", $sprite="java")
    ContainerDb(authdb, "Database", "PostgreSQL", "Holds user data and keycloak configuration", $sprite="postgresql")
}

System_Boundary(s1, "Authorization"){
    Container(author, "Authorization & Accounts API", "Python and FastAPI", "Manages subscriptions, user access, and features via RBAC.", $sprite="python")
}

System_Boundary(a2, "GOAT Application"){
    Container(applicationapi, "GOAT Core API", "Python and FastAPI", "Bundles GOAT-specific analyses and interacts with content metadata.", $sprite="python")
    Container(geoapi, "GEO API", "Python and FastAPI", "Provides geoservices: OGC Features and Vector tiles.", $sprite="python")

    ContainerDb(applicationdb, "Application Database", "PostgreSQL", "Holds application-specific base data, user accounts, and subscriptions.", $sprite="postgresql")

    Container(r5, "Routing API PT", "Java and R5", "Java engine handling travel-time calculation logic for public transport (PT).", $sprite="java")
    Container(goatrouting, "Routing API Car/Walking/Cycling", "Python and FastAPI", "Python engine using Numba for travel-time calculation (car, walking, cycling).", $sprite="python")
}

' Relations
Rel(auth, authdb, "Reads/Writes", "JDBC")
Rel(author, applicationdb, "Reads/Writes", "SQLAlchemy")
Rel(applicationapi, applicationdb, "Reads/Writes", "SQLAlchemy")
Rel(geoapi, applicationdb, "Reads", "SQLAlchemy")

Rel_L(s1, a1, "")
Rel_L(a1, s1, "")

Rel(applicationapi, r5, "HTTP (Private)")
Rel(applicationapi, goatrouting, "HTTP (Private)")

Rel(user, c1, "")
Rel(c1, a1, "")
Rel(c1, s1, "")
Rel_L(s1, a2, "")
Rel_R(a2, s1, "")

@enduml