from enum import Enum

class ColorRangeType(Enum):
    sequential = "sequential"
    diverging = "diverging"
    qualitative = "qualitative"
    single_hue = "single_hue"


data_viz_colors = {
    "aqua": "#12939A",
    "tumbleweed": "#DDB27C",
    "mule_fawn": "#88572C",
    "tree_poppy": "#FF991F",
    "flame": "#F15C17",
    "sapphire": "#223F9A",
    "orchid": "#DA70BF",
    "chathams_blue": "#125C77",
    "med_aquamarine": "#4DC19C",
    "crocodile": "#776E57",
    "java": "#17B8BE",
    "chalky": "#F6D18A",
    "light_taupe": "#B7885E",
    "peach_orange": "#FFCB99",
    "apricot": "#F89570",
    "portage": "#829AE3",
    "light_orchid": "#E79FD5",
    "blue_green": "#1E96BE",
    "bermuda": "#89DAC1",
    "cloudy": "#B3AD9E",
}

qua_colors = list(data_viz_colors.values())

qualitative_colors = {
    "Set2": [
        {
            "name": "Set2 1",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#66c2a5", "#fc8d62", "#8da0cb"],
        },
        {
            "name": "Set2 2",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3"],
        },
        {
            "name": "Set2 3",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3", "#a6d854"],
        },
        {
            "name": "Set2 4",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#66c2a5",
                "#fc8d62",
                "#8da0cb",
                "#e78ac3",
                "#a6d854",
                "#ffd92f",
            ],
        },
        {
            "name": "Set2 5",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#66c2a5",
                "#fc8d62",
                "#8da0cb",
                "#e78ac3",
                "#a6d854",
                "#ffd92f",
                "#e5c494",
            ],
        },
        {
            "name": "Set2 6",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#66c2a5",
                "#fc8d62",
                "#8da0cb",
                "#e78ac3",
                "#a6d854",
                "#ffd92f",
                "#e5c494",
                "#b3b3b3",
            ],
        },
    ],
    "Accent": [
        {
            "name": "Accent 1",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#7fc97f", "#beaed4", "#fdc086"],
        },
        {
            "name": "Accent 2",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#7fc97f", "#beaed4", "#fdc086", "#ffff99"],
        },
        {
            "name": "Accent 3",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#7fc97f", "#beaed4", "#fdc086", "#ffff99", "#386cb0"],
        },
        {
            "name": "Accent 4",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#7fc97f",
                "#beaed4",
                "#fdc086",
                "#ffff99",
                "#386cb0",
                "#f0027f",
            ],
        },
        {
            "name": "Accent 5",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#7fc97f",
                "#beaed4",
                "#fdc086",
                "#ffff99",
                "#386cb0",
                "#f0027f",
                "#bf5b17",
            ],
        },
        {
            "name": "Accent 6",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#7fc97f",
                "#beaed4",
                "#fdc086",
                "#ffff99",
                "#386cb0",
                "#f0027f",
                "#bf5b17",
                "#666666",
            ],
        },
    ],
    "Set1": [
        {
            "name": "Set1 1",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#e41a1c", "#377eb8", "#4daf4a"],
        },
        {
            "name": "Set1 2",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#e41a1c", "#377eb8", "#4daf4a", "#984ea3"],
        },
        {
            "name": "Set1 3",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00"],
        },
        {
            "name": "Set1 4",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#e41a1c",
                "#377eb8",
                "#4daf4a",
                "#984ea3",
                "#ff7f00",
                "#ffff33",
            ],
        },
        {
            "name": "Set1 5",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#e41a1c",
                "#377eb8",
                "#4daf4a",
                "#984ea3",
                "#ff7f00",
                "#ffff33",
                "#a65628",
            ],
        },
        {
            "name": "Set1 6",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#e41a1c",
                "#377eb8",
                "#4daf4a",
                "#984ea3",
                "#ff7f00",
                "#ffff33",
                "#a65628",
                "#f781bf",
            ],
        },
        {
            "name": "Set1 7",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#e41a1c",
                "#377eb8",
                "#4daf4a",
                "#984ea3",
                "#ff7f00",
                "#ffff33",
                "#a65628",
                "#f781bf",
                "#999999",
            ],
        },
    ],
    "Set3": [
        {
            "name": "Set3 1",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#8dd3c7", "#ffffb3", "#bebada"],
        },
        {
            "name": "Set3 2",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#8dd3c7", "#ffffb3", "#bebada", "#fb8072"],
        },
        {
            "name": "Set3 3",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#8dd3c7", "#ffffb3", "#bebada", "#fb8072", "#80b1d3"],
        },
        {
            "name": "Set3 4",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#8dd3c7",
                "#ffffb3",
                "#bebada",
                "#fb8072",
                "#80b1d3",
                "#fdb462",
            ],
        },
        {
            "name": "Set3 5",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#8dd3c7",
                "#ffffb3",
                "#bebada",
                "#fb8072",
                "#80b1d3",
                "#fdb462",
                "#b3de69",
            ],
        },
        {
            "name": "Set3 6",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#8dd3c7",
                "#ffffb3",
                "#bebada",
                "#fb8072",
                "#80b1d3",
                "#fdb462",
                "#b3de69",
                "#fccde5",
            ],
        },
        {
            "name": "Set3 7",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#8dd3c7",
                "#ffffb3",
                "#bebada",
                "#fb8072",
                "#80b1d3",
                "#fdb462",
                "#b3de69",
                "#fccde5",
                "#d9d9d9",
            ],
        },
        {
            "name": "Set3 8",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#8dd3c7",
                "#ffffb3",
                "#bebada",
                "#fb8072",
                "#80b1d3",
                "#fdb462",
                "#b3de69",
                "#fccde5",
                "#d9d9d9",
                "#bc80bd",
            ],
        },
        {
            "name": "Set3 9",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#8dd3c7",
                "#ffffb3",
                "#bebada",
                "#fb8072",
                "#80b1d3",
                "#fdb462",
                "#b3de69",
                "#fccde5",
                "#d9d9d9",
                "#bc80bd",
                "#ccebc5",
            ],
        },
        {
            "name": "Set3 10",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#8dd3c7",
                "#ffffb3",
                "#bebada",
                "#fb8072",
                "#80b1d3",
                "#fdb462",
                "#b3de69",
                "#fccde5",
                "#d9d9d9",
                "#bc80bd",
                "#ccebc5",
                "#ffed6f",
            ],
        },
    ],
    "Dark2": [
        {
            "name": "Dark2 1",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#1b9e77", "#d95f02", "#7570b3"],
        },
        {
            "name": "Dark2 2",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#1b9e77", "#d95f02", "#7570b3", "#e7298a"],
        },
        {
            "name": "Dark2 3",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#1b9e77", "#d95f02", "#7570b3", "#e7298a", "#66a61e"],
        },
        {
            "name": "Dark2 4",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#1b9e77",
                "#d95f02",
                "#7570b3",
                "#e7298a",
                "#66a61e",
                "#e6ab02",
            ],
        },
        {
            "name": "Dark2 5",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#1b9e77",
                "#d95f02",
                "#7570b3",
                "#e7298a",
                "#66a61e",
                "#e6ab02",
                "#a6761d",
            ],
        },
        {
            "name": "Dark2 6",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#1b9e77",
                "#d95f02",
                "#7570b3",
                "#e7298a",
                "#66a61e",
                "#e6ab02",
                "#a6761d",
                "#666666",
            ],
        },
    ],
    "Paired": [
        {
            "name": "Paired 1",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#a6cee3", "#1f78b4", "#b2df8a"],
        },
        {
            "name": "Paired 2",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#a6cee3", "#1f78b4", "#b2df8a", "#33a02c"],
        },
        {
            "name": "Paired 3",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99"],
        },
        {
            "name": "Paired 4",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#a6cee3",
                "#1f78b4",
                "#b2df8a",
                "#33a02c",
                "#fb9a99",
                "#e31a1c",
            ],
        },
        {
            "name": "Paired 5",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#a6cee3",
                "#1f78b4",
                "#b2df8a",
                "#33a02c",
                "#fb9a99",
                "#e31a1c",
                "#fdbf6f",
            ],
        },
        {
            "name": "Paired 6",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#a6cee3",
                "#1f78b4",
                "#b2df8a",
                "#33a02c",
                "#fb9a99",
                "#e31a1c",
                "#fdbf6f",
                "#ff7f00",
            ],
        },
        {
            "name": "Paired 7",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#a6cee3",
                "#1f78b4",
                "#b2df8a",
                "#33a02c",
                "#fb9a99",
                "#e31a1c",
                "#fdbf6f",
                "#ff7f00",
                "#cab2d6",
            ],
        },
        {
            "name": "Paired 8",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#a6cee3",
                "#1f78b4",
                "#b2df8a",
                "#33a02c",
                "#fb9a99",
                "#e31a1c",
                "#fdbf6f",
                "#ff7f00",
                "#cab2d6",
                "#6a3d9a",
            ],
        },
        {
            "name": "Paired 9",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#a6cee3",
                "#1f78b4",
                "#b2df8a",
                "#33a02c",
                "#fb9a99",
                "#e31a1c",
                "#fdbf6f",
                "#ff7f00",
                "#cab2d6",
                "#6a3d9a",
                "#ffff99",
            ],
        },
        {
            "name": "Paired 10",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#a6cee3",
                "#1f78b4",
                "#b2df8a",
                "#33a02c",
                "#fb9a99",
                "#e31a1c",
                "#fdbf6f",
                "#ff7f00",
                "#cab2d6",
                "#6a3d9a",
                "#ffff99",
                "#b15928",
            ],
        },
    ],
    "Pastel2": [
        {
            "name": "Pastel2 1",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#b3e2cd", "#fdcdac", "#cbd5e8"],
        },
        {
            "name": "Pastel2 2",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#b3e2cd", "#fdcdac", "#cbd5e8", "#f4cae4"],
        },
        {
            "name": "Pastel2 3",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#b3e2cd", "#fdcdac", "#cbd5e8", "#f4cae4", "#e6f5c9"],
        },
        {
            "name": "Pastel2 4",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#b3e2cd",
                "#fdcdac",
                "#cbd5e8",
                "#f4cae4",
                "#e6f5c9",
                "#fff2ae",
            ],
        },
        {
            "name": "Pastel2 5",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#b3e2cd",
                "#fdcdac",
                "#cbd5e8",
                "#f4cae4",
                "#e6f5c9",
                "#fff2ae",
                "#f1e2cc",
            ],
        },
        {
            "name": "Pastel2 6",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#b3e2cd",
                "#fdcdac",
                "#cbd5e8",
                "#f4cae4",
                "#e6f5c9",
                "#fff2ae",
                "#f1e2cc",
                "#cccccc",
            ],
        },
    ],
    "Pastel1": [
        {
            "name": "Pastel1 1",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#fbb4ae", "#b3cde3", "#ccebc5"],
        },
        {
            "name": "Pastel1 2",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#fbb4ae", "#b3cde3", "#ccebc5", "#decbe4"],
        },
        {
            "name": "Pastel1 3",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": ["#fbb4ae", "#b3cde3", "#ccebc5", "#decbe4", "#fed9a6"],
        },
        {
            "name": "Pastel1 4",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#fbb4ae",
                "#b3cde3",
                "#ccebc5",
                "#decbe4",
                "#fed9a6",
                "#ffffcc",
            ],
        },
        {
            "name": "Pastel1 5",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#fbb4ae",
                "#b3cde3",
                "#ccebc5",
                "#decbe4",
                "#fed9a6",
                "#ffffcc",
                "#e5d8bd",
            ],
        },
        {
            "name": "Pastel1 6",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#fbb4ae",
                "#b3cde3",
                "#ccebc5",
                "#decbe4",
                "#fed9a6",
                "#ffffcc",
                "#e5d8bd",
                "#fddaec",
            ],
        },
        {
            "name": "Pastel1 7",
            "type": "qualitative",
            "category": "Colorbrewer",
            "colors": [
                "#fbb4ae",
                "#b3cde3",
                "#ccebc5",
                "#decbe4",
                "#fed9a6",
                "#ffffcc",
                "#e5d8bd",
                "#fddaec",
                "#f2f2f2",
            ],
        },
    ],
    "uber_qualitative": [
        {
            "name": "Uber Viz Qualitative 0",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:3],
        },
        {
            "name": "Uber Viz Qualitative 0.5",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:4],
        },
        {
            "name": "Uber Viz Qualitative 1",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:5],
        },
        {
            "name": "Uber Viz Qualitative 1.2",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:6],
        },
        {
            "name": "Uber Viz Qualitative 1.4",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:7],
        },
        {
            "name": "Uber Viz Qualitative 1.6",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:8],
        },
        {
            "name": "Uber Viz Qualitative 1.8",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:9],
        },
        {
            "name": "Uber Viz Qualitative 2",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:10],
        },
        {
            "name": "Uber Viz Qualitative 3",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:15],
        },
        {
            "name": "Uber Viz Qualitative 4",
            "type": "qualitative",
            "category": "Uber",
            "colors": qua_colors[:20],
        },
    ],
}


single_hue_colors = {
    "Oranges": [
        {
            "name": "Oranges 1",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#fee6ce", "#fdae6b", "#e6550d"],
        },
        {
            "name": "Oranges 2",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#feedde", "#fdbe85", "#fd8d3c", "#d94701"],
        },
        {
            "name": "Oranges 3",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#feedde", "#fdbe85", "#fd8d3c", "#e6550d", "#a63603"],
        },
        {
            "name": "Oranges 4",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#feedde",
                "#fdd0a2",
                "#fdae6b",
                "#fd8d3c",
                "#e6550d",
                "#a63603",
            ],
        },
        {
            "name": "Oranges 5",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#feedde",
                "#fdd0a2",
                "#fdae6b",
                "#fd8d3c",
                "#f16913",
                "#d94801",
                "#8c2d04",
            ],
        },
        {
            "name": "Oranges 6",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#fff5eb",
                "#fee6ce",
                "#fdd0a2",
                "#fdae6b",
                "#fd8d3c",
                "#f16913",
                "#d94801",
                "#8c2d04",
            ],
        },
        {
            "name": "Oranges 7",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#fff5eb",
                "#fee6ce",
                "#fdd0a2",
                "#fdae6b",
                "#fd8d3c",
                "#f16913",
                "#d94801",
                "#a63603",
                "#7f2704",
            ],
        },
    ],
    "Greens": [
        {
            "name": "Greens 1",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#e5f5e0", "#a1d99b", "#31a354"],
        },
        {
            "name": "Greens 2",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#edf8e9", "#bae4b3", "#74c476", "#238b45"],
        },
        {
            "name": "Greens 3",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#edf8e9", "#bae4b3", "#74c476", "#31a354", "#006d2c"],
        },
        {
            "name": "Greens 4",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#edf8e9",
                "#c7e9c0",
                "#a1d99b",
                "#74c476",
                "#31a354",
                "#006d2c",
            ],
        },
        {
            "name": "Greens 5",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#edf8e9",
                "#c7e9c0",
                "#a1d99b",
                "#74c476",
                "#41ab5d",
                "#238b45",
                "#005a32",
            ],
        },
        {
            "name": "Greens 6",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#f7fcf5",
                "#e5f5e0",
                "#c7e9c0",
                "#a1d99b",
                "#74c476",
                "#41ab5d",
                "#238b45",
                "#005a32",
            ],
        },
        {
            "name": "Greens 7",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#f7fcf5",
                "#e5f5e0",
                "#c7e9c0",
                "#a1d99b",
                "#74c476",
                "#41ab5d",
                "#238b45",
                "#006d2c",
                "#00441b",
            ],
        },
    ],
    "Purples": [
        {
            "name": "Purples 1",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#efedf5", "#bcbddc", "#756bb1"],
        },
        {
            "name": "Purples 2",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#f2f0f7", "#cbc9e2", "#9e9ac8", "#6a51a3"],
        },
        {
            "name": "Purples 3",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#f2f0f7", "#cbc9e2", "#9e9ac8", "#756bb1", "#54278f"],
        },
        {
            "name": "Purples 4",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#f2f0f7",
                "#dadaeb",
                "#bcbddc",
                "#9e9ac8",
                "#756bb1",
                "#54278f",
            ],
        },
        {
            "name": "Purples 5",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#f2f0f7",
                "#dadaeb",
                "#bcbddc",
                "#9e9ac8",
                "#807dba",
                "#6a51a3",
                "#4a1486",
            ],
        },
        {
            "name": "Purples 6",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#fcfbfd",
                "#efedf5",
                "#dadaeb",
                "#bcbddc",
                "#9e9ac8",
                "#807dba",
                "#6a51a3",
                "#4a1486",
            ],
        },
        {
            "name": "Purples 7",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#fcfbfd",
                "#efedf5",
                "#dadaeb",
                "#bcbddc",
                "#9e9ac8",
                "#807dba",
                "#6a51a3",
                "#54278f",
                "#3f007d",
            ],
        },
    ],
    "Blues": [
        {
            "name": "Blues 1",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#deebf7", "#9ecae1", "#3182bd"],
        },
        {
            "name": "Blues 2",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#eff3ff", "#bdd7e7", "#6baed6", "#2171b5"],
        },
        {
            "name": "Blues 3",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#eff3ff", "#bdd7e7", "#6baed6", "#3182bd", "#08519c"],
        },
        {
            "name": "Blues 4",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#eff3ff",
                "#c6dbef",
                "#9ecae1",
                "#6baed6",
                "#3182bd",
                "#08519c",
            ],
        },
        {
            "name": "Blues 5",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#eff3ff",
                "#c6dbef",
                "#9ecae1",
                "#6baed6",
                "#4292c6",
                "#2171b5",
                "#084594",
            ],
        },
        {
            "name": "Blues 6",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#f7fbff",
                "#deebf7",
                "#c6dbef",
                "#9ecae1",
                "#6baed6",
                "#4292c6",
                "#2171b5",
                "#084594",
            ],
        },
        {
            "name": "Blues 7",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#f7fbff",
                "#deebf7",
                "#c6dbef",
                "#9ecae1",
                "#6baed6",
                "#4292c6",
                "#2171b5",
                "#08519c",
                "#08306b",
            ],
        },
    ],
    "Greys": [
        {
            "name": "Greys 1",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#f0f0f0", "#bdbdbd", "#636363"],
        },
        {
            "name": "Greys 2",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#f7f7f7", "#cccccc", "#969696", "#525252"],
        },
        {
            "name": "Greys 3",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#f7f7f7", "#cccccc", "#969696", "#636363", "#252525"],
        },
        {
            "name": "Greys 4",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#f7f7f7",
                "#d9d9d9",
                "#bdbdbd",
                "#969696",
                "#636363",
                "#252525",
            ],
        },
        {
            "name": "Greys 5",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#f7f7f7",
                "#d9d9d9",
                "#bdbdbd",
                "#969696",
                "#737373",
                "#525252",
                "#252525",
            ],
        },
        {
            "name": "Greys 6",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#ffffff",
                "#f0f0f0",
                "#d9d9d9",
                "#bdbdbd",
                "#969696",
                "#737373",
                "#525252",
                "#252525",
            ],
        },
        {
            "name": "Greys 7",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#ffffff",
                "#f0f0f0",
                "#d9d9d9",
                "#bdbdbd",
                "#969696",
                "#737373",
                "#525252",
                "#252525",
                "#000000",
            ],
        },
    ],
    "Reds": [
        {
            "name": "Reds 1",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#fee0d2", "#fc9272", "#de2d26"],
        },
        {
            "name": "Reds 2",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#fee5d9", "#fcae91", "#fb6a4a", "#cb181d"],
        },
        {
            "name": "Reds 3",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": ["#fee5d9", "#fcae91", "#fb6a4a", "#de2d26", "#a50f15"],
        },
        {
            "name": "Reds 4",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#fee5d9",
                "#fcbba1",
                "#fc9272",
                "#fb6a4a",
                "#de2d26",
                "#a50f15",
            ],
        },
        {
            "name": "Reds 5",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#fee5d9",
                "#fcbba1",
                "#fc9272",
                "#fb6a4a",
                "#ef3b2c",
                "#cb181d",
                "#99000d",
            ],
        },
        {
            "name": "Reds 6",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#fff5f0",
                "#fee0d2",
                "#fcbba1",
                "#fc9272",
                "#fb6a4a",
                "#ef3b2c",
                "#cb181d",
                "#99000d",
            ],
        },
        {
            "name": "Reds 7",
            "type": "singlehue",
            "category": "Colorbrewer",
            "colors": [
                "#fff5f0",
                "#fee0d2",
                "#fcbba1",
                "#fc9272",
                "#fb6a4a",
                "#ef3b2c",
                "#cb181d",
                "#a50f15",
                "#67000d",
            ],
        },
    ],
}

sequential_colors = {
    "OrRd": [
        {
            "name": "OrRd 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#fee8c8", "#fdbb84", "#e34a33"],
        },
        {
            "name": "OrRd 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#fef0d9", "#fdcc8a", "#fc8d59", "#d7301f"],
        },
        {
            "name": "OrRd 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#fef0d9", "#fdcc8a", "#fc8d59", "#e34a33", "#b30000"],
        },
        {
            "name": "OrRd 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fef0d9",
                "#fdd49e",
                "#fdbb84",
                "#fc8d59",
                "#e34a33",
                "#b30000",
            ],
        },
        {
            "name": "OrRd 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fef0d9",
                "#fdd49e",
                "#fdbb84",
                "#fc8d59",
                "#ef6548",
                "#d7301f",
                "#990000",
            ],
        },
        {
            "name": "OrRd 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fff7ec",
                "#fee8c8",
                "#fdd49e",
                "#fdbb84",
                "#fc8d59",
                "#ef6548",
                "#d7301f",
                "#990000",
            ],
        },
        {
            "name": "OrRd 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fff7ec",
                "#fee8c8",
                "#fdd49e",
                "#fdbb84",
                "#fc8d59",
                "#ef6548",
                "#d7301f",
                "#b30000",
                "#7f0000",
            ],
        },
    ],
    "PuBu": [
        {
            "name": "PuBu 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ece7f2", "#a6bddb", "#2b8cbe"],
        },
        {
            "name": "PuBu 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#f1eef6", "#bdc9e1", "#74a9cf", "#0570b0"],
        },
        {
            "name": "PuBu 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#f1eef6", "#bdc9e1", "#74a9cf", "#2b8cbe", "#045a8d"],
        },
        {
            "name": "PuBu 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f1eef6",
                "#d0d1e6",
                "#a6bddb",
                "#74a9cf",
                "#2b8cbe",
                "#045a8d",
            ],
        },
        {
            "name": "PuBu 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f1eef6",
                "#d0d1e6",
                "#a6bddb",
                "#74a9cf",
                "#3690c0",
                "#0570b0",
                "#034e7b",
            ],
        },
        {
            "name": "PuBu 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fff7fb",
                "#ece7f2",
                "#d0d1e6",
                "#a6bddb",
                "#74a9cf",
                "#3690c0",
                "#0570b0",
                "#034e7b",
            ],
        },
        {
            "name": "PuBu 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fff7fb",
                "#ece7f2",
                "#d0d1e6",
                "#a6bddb",
                "#74a9cf",
                "#3690c0",
                "#0570b0",
                "#045a8d",
                "#023858",
            ],
        },
    ],
    "BuPu": [
        {
            "name": "BuPu 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#e0ecf4", "#9ebcda", "#8856a7"],
        },
        {
            "name": "BuPu 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#edf8fb", "#b3cde3", "#8c96c6", "#88419d"],
        },
        {
            "name": "BuPu 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#edf8fb", "#b3cde3", "#8c96c6", "#8856a7", "#810f7c"],
        },
        {
            "name": "BuPu 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#edf8fb",
                "#bfd3e6",
                "#9ebcda",
                "#8c96c6",
                "#8856a7",
                "#810f7c",
            ],
        },
        {
            "name": "BuPu 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#edf8fb",
                "#bfd3e6",
                "#9ebcda",
                "#8c96c6",
                "#8c6bb1",
                "#88419d",
                "#6e016b",
            ],
        },
        {
            "name": "BuPu 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f7fcfd",
                "#e0ecf4",
                "#bfd3e6",
                "#9ebcda",
                "#8c96c6",
                "#8c6bb1",
                "#88419d",
                "#6e016b",
            ],
        },
        {
            "name": "BuPu 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f7fcfd",
                "#e0ecf4",
                "#bfd3e6",
                "#9ebcda",
                "#8c96c6",
                "#8c6bb1",
                "#88419d",
                "#810f7c",
                "#4d004b",
            ],
        },
    ],
    "BuGn": [
        {
            "name": "BuGn 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#e5f5f9", "#99d8c9", "#2ca25f"],
        },
        {
            "name": "BuGn 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#edf8fb", "#b2e2e2", "#66c2a4", "#238b45"],
        },
        {
            "name": "BuGn 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#edf8fb", "#b2e2e2", "#66c2a4", "#2ca25f", "#006d2c"],
        },
        {
            "name": "BuGn 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#edf8fb",
                "#ccece6",
                "#99d8c9",
                "#66c2a4",
                "#2ca25f",
                "#006d2c",
            ],
        },
        {
            "name": "BuGn 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#edf8fb",
                "#ccece6",
                "#99d8c9",
                "#66c2a4",
                "#41ae76",
                "#238b45",
                "#005824",
            ],
        },
        {
            "name": "BuGn 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f7fcfd",
                "#e5f5f9",
                "#ccece6",
                "#99d8c9",
                "#66c2a4",
                "#41ae76",
                "#238b45",
                "#005824",
            ],
        },
        {
            "name": "BuGn 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f7fcfd",
                "#e5f5f9",
                "#ccece6",
                "#99d8c9",
                "#66c2a4",
                "#41ae76",
                "#238b45",
                "#006d2c",
                "#00441b",
            ],
        },
    ],
    "YlOrBr": [
        {
            "name": "YlOrBr 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#fff7bc", "#fec44f", "#d95f0e"],
        },
        {
            "name": "YlOrBr 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ffffd4", "#fed98e", "#fe9929", "#cc4c02"],
        },
        {
            "name": "YlOrBr 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ffffd4", "#fed98e", "#fe9929", "#d95f0e", "#993404"],
        },
        {
            "name": "YlOrBr 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffd4",
                "#fee391",
                "#fec44f",
                "#fe9929",
                "#d95f0e",
                "#993404",
            ],
        },
        {
            "name": "YlOrBr 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffd4",
                "#fee391",
                "#fec44f",
                "#fe9929",
                "#ec7014",
                "#cc4c02",
                "#8c2d04",
            ],
        },
        {
            "name": "YlOrBr 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffe5",
                "#fff7bc",
                "#fee391",
                "#fec44f",
                "#fe9929",
                "#ec7014",
                "#cc4c02",
                "#8c2d04",
            ],
        },
        {
            "name": "YlOrBr 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffe5",
                "#fff7bc",
                "#fee391",
                "#fec44f",
                "#fe9929",
                "#ec7014",
                "#cc4c02",
                "#993404",
                "#662506",
            ],
        },
    ],
    "YlGn": [
        {
            "name": "YlGn 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#f7fcb9", "#addd8e", "#31a354"],
        },
        {
            "name": "YlGn 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ffffcc", "#c2e699", "#78c679", "#238443"],
        },
        {
            "name": "YlGn 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ffffcc", "#c2e699", "#78c679", "#31a354", "#006837"],
        },
        {
            "name": "YlGn 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffcc",
                "#d9f0a3",
                "#addd8e",
                "#78c679",
                "#31a354",
                "#006837",
            ],
        },
        {
            "name": "YlGn 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffcc",
                "#d9f0a3",
                "#addd8e",
                "#78c679",
                "#41ab5d",
                "#238443",
                "#005a32",
            ],
        },
        {
            "name": "YlGn 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffe5",
                "#f7fcb9",
                "#d9f0a3",
                "#addd8e",
                "#78c679",
                "#41ab5d",
                "#238443",
                "#005a32",
            ],
        },
        {
            "name": "YlGn 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffe5",
                "#f7fcb9",
                "#d9f0a3",
                "#addd8e",
                "#78c679",
                "#41ab5d",
                "#238443",
                "#006837",
                "#004529",
            ],
        },
    ],
    "RdPu": [
        {
            "name": "RdPu 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#fde0dd", "#fa9fb5", "#c51b8a"],
        },
        {
            "name": "RdPu 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#feebe2", "#fbb4b9", "#f768a1", "#ae017e"],
        },
        {
            "name": "RdPu 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#feebe2", "#fbb4b9", "#f768a1", "#c51b8a", "#7a0177"],
        },
        {
            "name": "RdPu 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#feebe2",
                "#fcc5c0",
                "#fa9fb5",
                "#f768a1",
                "#c51b8a",
                "#7a0177",
            ],
        },
        {
            "name": "RdPu 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#feebe2",
                "#fcc5c0",
                "#fa9fb5",
                "#f768a1",
                "#dd3497",
                "#ae017e",
                "#7a0177",
            ],
        },
        {
            "name": "RdPu 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fff7f3",
                "#fde0dd",
                "#fcc5c0",
                "#fa9fb5",
                "#f768a1",
                "#dd3497",
                "#ae017e",
                "#7a0177",
            ],
        },
        {
            "name": "RdPu 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fff7f3",
                "#fde0dd",
                "#fcc5c0",
                "#fa9fb5",
                "#f768a1",
                "#dd3497",
                "#ae017e",
                "#7a0177",
                "#49006a",
            ],
        },
    ],
    "YlGnBu": [
        {
            "name": "YlGnBu 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#edf8b1", "#7fcdbb", "#2c7fb8"],
        },
        {
            "name": "YlGnBu 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ffffcc", "#a1dab4", "#41b6c4", "#225ea8"],
        },
        {
            "name": "YlGnBu 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ffffcc", "#a1dab4", "#41b6c4", "#2c7fb8", "#253494"],
        },
        {
            "name": "YlGnBu 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffcc",
                "#c7e9b4",
                "#7fcdbb",
                "#41b6c4",
                "#2c7fb8",
                "#253494",
            ],
        },
        {
            "name": "YlGnBu 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffcc",
                "#c7e9b4",
                "#7fcdbb",
                "#41b6c4",
                "#1d91c0",
                "#225ea8",
                "#0c2c84",
            ],
        },
        {
            "name": "YlGnBu 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffd9",
                "#edf8b1",
                "#c7e9b4",
                "#7fcdbb",
                "#41b6c4",
                "#1d91c0",
                "#225ea8",
                "#0c2c84",
            ],
        },
        {
            "name": "YlGnBu 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffd9",
                "#edf8b1",
                "#c7e9b4",
                "#7fcdbb",
                "#41b6c4",
                "#1d91c0",
                "#225ea8",
                "#253494",
                "#081d58",
            ],
        },
    ],
    "GnBu": [
        {
            "name": "GnBu 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#e0f3db", "#a8ddb5", "#43a2ca"],
        },
        {
            "name": "GnBu 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#f0f9e8", "#bae4bc", "#7bccc4", "#2b8cbe"],
        },
        {
            "name": "GnBu 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#f0f9e8", "#bae4bc", "#7bccc4", "#43a2ca", "#0868ac"],
        },
        {
            "name": "GnBu 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f0f9e8",
                "#ccebc5",
                "#a8ddb5",
                "#7bccc4",
                "#43a2ca",
                "#0868ac",
            ],
        },
        {
            "name": "GnBu 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f0f9e8",
                "#ccebc5",
                "#a8ddb5",
                "#7bccc4",
                "#4eb3d3",
                "#2b8cbe",
                "#08589e",
            ],
        },
        {
            "name": "GnBu 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f7fcf0",
                "#e0f3db",
                "#ccebc5",
                "#a8ddb5",
                "#7bccc4",
                "#4eb3d3",
                "#2b8cbe",
                "#08589e",
            ],
        },
        {
            "name": "GnBu 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f7fcf0",
                "#e0f3db",
                "#ccebc5",
                "#a8ddb5",
                "#7bccc4",
                "#4eb3d3",
                "#2b8cbe",
                "#0868ac",
                "#084081",
            ],
        },
    ],
    "YlOrRd": [
        {
            "name": "YlOrRd 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ffeda0", "#feb24c", "#f03b20"],
        },
        {
            "name": "YlOrRd 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ffffb2", "#fecc5c", "#fd8d3c", "#e31a1c"],
        },
        {
            "name": "YlOrRd 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ffffb2", "#fecc5c", "#fd8d3c", "#f03b20", "#bd0026"],
        },
        {
            "name": "YlOrRd 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffb2",
                "#fed976",
                "#feb24c",
                "#fd8d3c",
                "#f03b20",
                "#bd0026",
            ],
        },
        {
            "name": "YlOrRd 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffb2",
                "#fed976",
                "#feb24c",
                "#fd8d3c",
                "#fc4e2a",
                "#e31a1c",
                "#b10026",
            ],
        },
        {
            "name": "YlOrRd 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#ffffcc",
                "#ffeda0",
                "#fed976",
                "#feb24c",
                "#fd8d3c",
                "#fc4e2a",
                "#e31a1c",
                "#b10026",
            ],
        },
    ],
    "PuRd": [
        {
            "name": "PuRd 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#e7e1ef", "#c994c7", "#dd1c77"],
        },
        {
            "name": "PuRd 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#f1eef6", "#d7b5d8", "#df65b0", "#ce1256"],
        },
        {
            "name": "PuRd 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#f1eef6", "#d7b5d8", "#df65b0", "#dd1c77", "#980043"],
        },
        {
            "name": "PuRd 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f1eef6",
                "#d4b9da",
                "#c994c7",
                "#df65b0",
                "#dd1c77",
                "#980043",
            ],
        },
        {
            "name": "PuRd 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f1eef6",
                "#d4b9da",
                "#c994c7",
                "#df65b0",
                "#e7298a",
                "#ce1256",
                "#91003f",
            ],
        },
        {
            "name": "PuRd 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f7f4f9",
                "#e7e1ef",
                "#d4b9da",
                "#c994c7",
                "#df65b0",
                "#e7298a",
                "#ce1256",
                "#91003f",
            ],
        },
        {
            "name": "PuRd 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f7f4f9",
                "#e7e1ef",
                "#d4b9da",
                "#c994c7",
                "#df65b0",
                "#e7298a",
                "#ce1256",
                "#980043",
                "#67001f",
            ],
        },
    ],
    "PuBuGn": [
        {
            "name": "PuBuGn 1",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#ece2f0", "#a6bddb", "#1c9099"],
        },
        {
            "name": "PuBuGn 2",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#f6eff7", "#bdc9e1", "#67a9cf", "#02818a"],
        },
        {
            "name": "PuBuGn 3",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": ["#f6eff7", "#bdc9e1", "#67a9cf", "#1c9099", "#016c59"],
        },
        {
            "name": "PuBuGn 4",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f6eff7",
                "#d0d1e6",
                "#a6bddb",
                "#67a9cf",
                "#1c9099",
                "#016c59",
            ],
        },
        {
            "name": "PuBuGn 5",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#f6eff7",
                "#d0d1e6",
                "#a6bddb",
                "#67a9cf",
                "#3690c0",
                "#02818a",
                "#016450",
            ],
        },
        {
            "name": "PuBuGn 6",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fff7fb",
                "#ece2f0",
                "#d0d1e6",
                "#a6bddb",
                "#67a9cf",
                "#3690c0",
                "#02818a",
                "#016450",
            ],
        },
        {
            "name": "PuBuGn 7",
            "type": "sequential",
            "category": "Colorbrewer",
            "colors": [
                "#fff7fb",
                "#ece2f0",
                "#d0d1e6",
                "#a6bddb",
                "#67a9cf",
                "#3690c0",
                "#02818a",
                "#016c59",
                "#014636",
            ],
        },
    ],
    "uber_sequential": [
        {
            "name": "Uber Viz Sequential 1",
            "type": "sequential",
            "category": "Uber",
            "colors": ["#E6FAFA", "#89C6CA", "#00939C"],
        },
        {
            "name": "Uber Viz Sequential 2",
            "type": "sequential",
            "category": "Uber",
            "colors": ["#E6FAFA", "#AAD7DA", "#68B4BB", "#00939C"],
        },
        {
            "name": "Uber Viz Sequential 3",
            "type": "sequential",
            "category": "Uber",
            "colors": ["#E6FAFA", "#B8E0E1", "#89C6CA", "#56ACB3", "#00939C"],
        },
        {
            "name": "Uber Viz Sequential 4",
            "type": "sequential",
            "category": "Uber",
            "colors": [
                "#E6FAFA",
                "#C1E5E6",
                "#9DD0D4",
                "#75BBC1",
                "#4BA7AF",
                "#00939C",
            ],
        },
        {
            "name": "Uber Viz Sequential 5",
            "type": "sequential",
            "category": "Uber",
            "colors": [
                "#E6FAFA",
                "#C1E5E6",
                "#9DD0D4",
                "#75BBC1",
                "#4BA7AF",
                "#00939C",
                "#108188",
            ],
        },
        {
            "name": "Uber Viz Sequential 6",
            "type": "sequential",
            "category": "Uber",
            "colors": [
                "#E6FAFA",
                "#C1E5E6",
                "#9DD0D4",
                "#75BBC1",
                "#4BA7AF",
                "#00939C",
                "#108188",
                "#0E7077",
            ],
        },
    ],
}

diverging_colors = {
    "Spectral": [
        {
            "name": "Spectral 1",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#fc8d59", "#ffffbf", "#99d594"],
        },
        {
            "name": "Spectral 2",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#d7191c", "#fdae61", "#abdda4", "#2b83ba"],
        },
        {
            "name": "Spectral 3",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#d7191c", "#fdae61", "#ffffbf", "#abdda4", "#2b83ba"],
        },
        {
            "name": "Spectral 4",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d53e4f",
                "#fc8d59",
                "#fee08b",
                "#e6f598",
                "#99d594",
                "#3288bd",
            ],
        },
        {
            "name": "Spectral 5",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d53e4f",
                "#fc8d59",
                "#fee08b",
                "#ffffbf",
                "#e6f598",
                "#99d594",
                "#3288bd",
            ],
        },
        {
            "name": "Spectral 6",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d53e4f",
                "#f46d43",
                "#fdae61",
                "#fee08b",
                "#e6f598",
                "#abdda4",
                "#66c2a5",
                "#3288bd",
            ],
        },
        {
            "name": "Spectral 7",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d53e4f",
                "#f46d43",
                "#fdae61",
                "#fee08b",
                "#ffffbf",
                "#e6f598",
                "#abdda4",
                "#66c2a5",
                "#3288bd",
            ],
        },
        {
            "name": "Spectral 8",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#9e0142",
                "#d53e4f",
                "#f46d43",
                "#fdae61",
                "#fee08b",
                "#e6f598",
                "#abdda4",
                "#66c2a5",
                "#3288bd",
                "#5e4fa2",
            ],
        },
        {
            "name": "Spectral 9",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#9e0142",
                "#d53e4f",
                "#f46d43",
                "#fdae61",
                "#fee08b",
                "#ffffbf",
                "#e6f598",
                "#abdda4",
                "#66c2a5",
                "#3288bd",
                "#5e4fa2",
            ],
        },
    ],
    "RdYlGn": [
        {
            "name": "RdYlGn 1",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#fc8d59", "#ffffbf", "#91cf60"],
        },
        {
            "name": "RdYlGn 2",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#d7191c", "#fdae61", "#a6d96a", "#1a9641"],
        },
        {
            "name": "RdYlGn 3",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#d7191c", "#fdae61", "#ffffbf", "#a6d96a", "#1a9641"],
        },
        {
            "name": "RdYlGn 4",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d73027",
                "#fc8d59",
                "#fee08b",
                "#d9ef8b",
                "#91cf60",
                "#1a9850",
            ],
        },
        {
            "name": "RdYlGn 5",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d73027",
                "#fc8d59",
                "#fee08b",
                "#ffffbf",
                "#d9ef8b",
                "#91cf60",
                "#1a9850",
            ],
        },
        {
            "name": "RdYlGn 6",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d73027",
                "#f46d43",
                "#fdae61",
                "#fee08b",
                "#d9ef8b",
                "#a6d96a",
                "#66bd63",
                "#1a9850",
            ],
        },
        {
            "name": "RdYlGn 7",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d73027",
                "#f46d43",
                "#fdae61",
                "#fee08b",
                "#ffffbf",
                "#d9ef8b",
                "#a6d96a",
                "#66bd63",
                "#1a9850",
            ],
        },
        {
            "name": "RdYlGn 8",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#a50026",
                "#d73027",
                "#f46d43",
                "#fdae61",
                "#fee08b",
                "#d9ef8b",
                "#a6d96a",
                "#66bd63",
                "#1a9850",
                "#006837",
            ],
        },
        {
            "name": "RdYlGn 9",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#a50026",
                "#d73027",
                "#f46d43",
                "#fdae61",
                "#fee08b",
                "#ffffbf",
                "#d9ef8b",
                "#a6d96a",
                "#66bd63",
                "#1a9850",
                "#006837",
            ],
        },
    ],
    "RdBu": [
        {
            "name": "RdBu 1",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#ef8a62", "#f7f7f7", "#67a9cf"],
        },
        {
            "name": "RdBu 2",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#ca0020", "#f4a582", "#92c5de", "#0571b0"],
        },
        {
            "name": "RdBu 3",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#ca0020", "#f4a582", "#f7f7f7", "#92c5de", "#0571b0"],
        },
        {
            "name": "RdBu 4",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b2182b",
                "#ef8a62",
                "#fddbc7",
                "#d1e5f0",
                "#67a9cf",
                "#2166ac",
            ],
        },
        {
            "name": "RdBu 5",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b2182b",
                "#ef8a62",
                "#fddbc7",
                "#f7f7f7",
                "#d1e5f0",
                "#67a9cf",
                "#2166ac",
            ],
        },
        {
            "name": "RdBu 6",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b2182b",
                "#d6604d",
                "#f4a582",
                "#fddbc7",
                "#d1e5f0",
                "#92c5de",
                "#4393c3",
                "#2166ac",
            ],
        },
        {
            "name": "RdBu 7",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b2182b",
                "#d6604d",
                "#f4a582",
                "#fddbc7",
                "#f7f7f7",
                "#d1e5f0",
                "#92c5de",
                "#4393c3",
                "#2166ac",
            ],
        },
        {
            "name": "RdBu 8",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#67001f",
                "#b2182b",
                "#d6604d",
                "#f4a582",
                "#fddbc7",
                "#d1e5f0",
                "#92c5de",
                "#4393c3",
                "#2166ac",
                "#053061",
            ],
        },
        {
            "name": "RdBu 9",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#67001f",
                "#b2182b",
                "#d6604d",
                "#f4a582",
                "#fddbc7",
                "#f7f7f7",
                "#d1e5f0",
                "#92c5de",
                "#4393c3",
                "#2166ac",
                "#053061",
            ],
        },
    ],
    "PiYG": [
        {
            "name": "PiYG 1",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#e9a3c9", "#f7f7f7", "#a1d76a"],
        },
        {
            "name": "PiYG 2",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#d01c8b", "#f1b6da", "#b8e186", "#4dac26"],
        },
        {
            "name": "PiYG 3",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#d01c8b", "#f1b6da", "#f7f7f7", "#b8e186", "#4dac26"],
        },
        {
            "name": "PiYG 4",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#c51b7d",
                "#e9a3c9",
                "#fde0ef",
                "#e6f5d0",
                "#a1d76a",
                "#4d9221",
            ],
        },
        {
            "name": "PiYG 5",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#c51b7d",
                "#e9a3c9",
                "#fde0ef",
                "#f7f7f7",
                "#e6f5d0",
                "#a1d76a",
                "#4d9221",
            ],
        },
        {
            "name": "PiYG 6",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#c51b7d",
                "#de77ae",
                "#f1b6da",
                "#fde0ef",
                "#e6f5d0",
                "#b8e186",
                "#7fbc41",
                "#4d9221",
            ],
        },
        {
            "name": "PiYG 7",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#c51b7d",
                "#de77ae",
                "#f1b6da",
                "#fde0ef",
                "#f7f7f7",
                "#e6f5d0",
                "#b8e186",
                "#7fbc41",
                "#4d9221",
            ],
        },
        {
            "name": "PiYG 8",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#8e0152",
                "#c51b7d",
                "#de77ae",
                "#f1b6da",
                "#fde0ef",
                "#e6f5d0",
                "#b8e186",
                "#7fbc41",
                "#4d9221",
                "#276419",
            ],
        },
        {
            "name": "PiYG 9",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#8e0152",
                "#c51b7d",
                "#de77ae",
                "#f1b6da",
                "#fde0ef",
                "#f7f7f7",
                "#e6f5d0",
                "#b8e186",
                "#7fbc41",
                "#4d9221",
                "#276419",
            ],
        },
    ],
    "PRGn": [
        {
            "name": "PRGn 1",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#af8dc3", "#f7f7f7", "#7fbf7b"],
        },
        {
            "name": "PRGn 2",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#7b3294", "#c2a5cf", "#a6dba0", "#008837"],
        },
        {
            "name": "PRGn 3",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#7b3294", "#c2a5cf", "#f7f7f7", "#a6dba0", "#008837"],
        },
        {
            "name": "PRGn 4",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#762a83",
                "#af8dc3",
                "#e7d4e8",
                "#d9f0d3",
                "#7fbf7b",
                "#1b7837",
            ],
        },
        {
            "name": "PRGn 5",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#762a83",
                "#af8dc3",
                "#e7d4e8",
                "#f7f7f7",
                "#d9f0d3",
                "#7fbf7b",
                "#1b7837",
            ],
        },
        {
            "name": "PRGn 6",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#762a83",
                "#9970ab",
                "#c2a5cf",
                "#e7d4e8",
                "#d9f0d3",
                "#a6dba0",
                "#5aae61",
                "#1b7837",
            ],
        },
        {
            "name": "PRGn 7",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#762a83",
                "#9970ab",
                "#c2a5cf",
                "#e7d4e8",
                "#f7f7f7",
                "#d9f0d3",
                "#a6dba0",
                "#5aae61",
                "#1b7837",
            ],
        },
        {
            "name": "PRGn 8",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#40004b",
                "#762a83",
                "#9970ab",
                "#c2a5cf",
                "#e7d4e8",
                "#d9f0d3",
                "#a6dba0",
                "#5aae61",
                "#1b7837",
                "#00441b",
            ],
        },
        {
            "name": "PRGn 9",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#40004b",
                "#762a83",
                "#9970ab",
                "#c2a5cf",
                "#e7d4e8",
                "#f7f7f7",
                "#d9f0d3",
                "#a6dba0",
                "#5aae61",
                "#1b7837",
                "#00441b",
            ],
        },
    ],
    "RdYlBu": [
        {
            "name": "RdYlBu 1",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#fc8d59", "#ffffbf", "#91bfdb"],
        },
        {
            "name": "RdYlBu 2",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#d7191c", "#fdae61", "#abd9e9", "#2c7bb6"],
        },
        {
            "name": "RdYlBu 3",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#d7191c", "#fdae61", "#ffffbf", "#abd9e9", "#2c7bb6"],
        },
        {
            "name": "RdYlBu 4",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d73027",
                "#fc8d59",
                "#fee090",
                "#e0f3f8",
                "#91bfdb",
                "#4575b4",
            ],
        },
        {
            "name": "RdYlBu 5",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d73027",
                "#fc8d59",
                "#fee090",
                "#ffffbf",
                "#e0f3f8",
                "#91bfdb",
                "#4575b4",
            ],
        },
        {
            "name": "RdYlBu 6",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d73027",
                "#f46d43",
                "#fdae61",
                "#fee090",
                "#e0f3f8",
                "#abd9e9",
                "#74add1",
                "#4575b4",
            ],
        },
        {
            "name": "RdYlBu 7",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#d73027",
                "#f46d43",
                "#fdae61",
                "#fee090",
                "#ffffbf",
                "#e0f3f8",
                "#abd9e9",
                "#74add1",
                "#4575b4",
            ],
        },
        {
            "name": "RdYlBu 8",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#a50026",
                "#d73027",
                "#f46d43",
                "#fdae61",
                "#fee090",
                "#e0f3f8",
                "#abd9e9",
                "#74add1",
                "#4575b4",
                "#313695",
            ],
        },
        {
            "name": "RdYlBu 9",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#a50026",
                "#d73027",
                "#f46d43",
                "#fdae61",
                "#fee090",
                "#ffffbf",
                "#e0f3f8",
                "#abd9e9",
                "#74add1",
                "#4575b4",
                "#313695",
            ],
        },
    ],
    "BrBG": [
        {
            "name": "BrBG 1",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#d8b365", "#f5f5f5", "#5ab4ac"],
        },
        {
            "name": "BrBG 2",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#a6611a", "#dfc27d", "#80cdc1", "#018571"],
        },
        {
            "name": "BrBG 3",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#a6611a", "#dfc27d", "#f5f5f5", "#80cdc1", "#018571"],
        },
        {
            "name": "BrBG 4",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#8c510a",
                "#d8b365",
                "#f6e8c3",
                "#c7eae5",
                "#5ab4ac",
                "#01665e",
            ],
        },
        {
            "name": "BrBG 5",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#8c510a",
                "#d8b365",
                "#f6e8c3",
                "#f5f5f5",
                "#c7eae5",
                "#5ab4ac",
                "#01665e",
            ],
        },
        {
            "name": "BrBG 6",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#8c510a",
                "#bf812d",
                "#dfc27d",
                "#f6e8c3",
                "#c7eae5",
                "#80cdc1",
                "#35978f",
                "#01665e",
            ],
        },
        {
            "name": "BrBG 7",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#8c510a",
                "#bf812d",
                "#dfc27d",
                "#f6e8c3",
                "#f5f5f5",
                "#c7eae5",
                "#80cdc1",
                "#35978f",
                "#01665e",
            ],
        },
        {
            "name": "BrBG 8",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#543005",
                "#8c510a",
                "#bf812d",
                "#dfc27d",
                "#f6e8c3",
                "#c7eae5",
                "#80cdc1",
                "#35978f",
                "#01665e",
                "#003c30",
            ],
        },
        {
            "name": "BrBG 9",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#543005",
                "#8c510a",
                "#bf812d",
                "#dfc27d",
                "#f6e8c3",
                "#f5f5f5",
                "#c7eae5",
                "#80cdc1",
                "#35978f",
                "#01665e",
                "#003c30",
            ],
        },
    ],
    "RdGy": [
        {
            "name": "RdGy 1",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#ef8a62", "#ffffff", "#999999"],
        },
        {
            "name": "RdGy 2",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#ca0020", "#f4a582", "#bababa", "#404040"],
        },
        {
            "name": "RdGy 3",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#ca0020", "#f4a582", "#ffffff", "#bababa", "#404040"],
        },
        {
            "name": "RdGy 4",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b2182b",
                "#ef8a62",
                "#fddbc7",
                "#e0e0e0",
                "#999999",
                "#4d4d4d",
            ],
        },
        {
            "name": "RdGy 5",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b2182b",
                "#ef8a62",
                "#fddbc7",
                "#ffffff",
                "#e0e0e0",
                "#999999",
                "#4d4d4d",
            ],
        },
        {
            "name": "RdGy 6",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b2182b",
                "#d6604d",
                "#f4a582",
                "#fddbc7",
                "#e0e0e0",
                "#bababa",
                "#878787",
                "#4d4d4d",
            ],
        },
        {
            "name": "RdGy 7",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b2182b",
                "#d6604d",
                "#f4a582",
                "#fddbc7",
                "#ffffff",
                "#e0e0e0",
                "#bababa",
                "#878787",
                "#4d4d4d",
            ],
        },
        {
            "name": "RdGy 8",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#67001f",
                "#b2182b",
                "#d6604d",
                "#f4a582",
                "#fddbc7",
                "#e0e0e0",
                "#bababa",
                "#878787",
                "#4d4d4d",
                "#1a1a1a",
            ],
        },
        {
            "name": "RdGy 9",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#67001f",
                "#b2182b",
                "#d6604d",
                "#f4a582",
                "#fddbc7",
                "#ffffff",
                "#e0e0e0",
                "#bababa",
                "#878787",
                "#4d4d4d",
                "#1a1a1a",
            ],
        },
    ],
    "PuOr": [
        {
            "name": "PuOr 1",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#f1a340", "#f7f7f7", "#998ec3"],
        },
        {
            "name": "PuOr 2",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#e66101", "#fdb863", "#b2abd2", "#5e3c99"],
        },
        {
            "name": "PuOr 3",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": ["#e66101", "#fdb863", "#f7f7f7", "#b2abd2", "#5e3c99"],
        },
        {
            "name": "PuOr 4",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b35806",
                "#f1a340",
                "#fee0b6",
                "#d8daeb",
                "#998ec3",
                "#542788",
            ],
        },
        {
            "name": "PuOr 5",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b35806",
                "#f1a340",
                "#fee0b6",
                "#f7f7f7",
                "#d8daeb",
                "#998ec3",
                "#542788",
            ],
        },
        {
            "name": "PuOr 6",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b35806",
                "#e08214",
                "#fdb863",
                "#fee0b6",
                "#d8daeb",
                "#b2abd2",
                "#8073ac",
                "#542788",
            ],
        },
        {
            "name": "PuOr 7",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#b35806",
                "#e08214",
                "#fdb863",
                "#fee0b6",
                "#f7f7f7",
                "#d8daeb",
                "#b2abd2",
                "#8073ac",
                "#542788",
            ],
        },
        {
            "name": "PuOr 8",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#7f3b08",
                "#b35806",
                "#e08214",
                "#fdb863",
                "#fee0b6",
                "#d8daeb",
                "#b2abd2",
                "#8073ac",
                "#542788",
                "#2d004b",
            ],
        },
        {
            "name": "PuOr 9",
            "type": "diverging",
            "category": "Colorbrewer",
            "colors": [
                "#7f3b08",
                "#b35806",
                "#e08214",
                "#fdb863",
                "#fee0b6",
                "#f7f7f7",
                "#d8daeb",
                "#b2abd2",
                "#8073ac",
                "#542788",
                "#2d004b",
            ],
        },
    ],
    "uber_diverging": [
        {
            "name": "Uber Viz Diverging 0",
            "type": "diverging",
            "category": "Uber",
            "colors": ["#C22E00", "#FEEEE8", "#00939C"][::-1],
        },
        {
            "name": "Uber Viz Diverging 0.5",
            "type": "diverging",
            "category": "Uber",
            "colors": ["#C22E00", "#EFBEAE", "#A2D4D7", "#00939C"][::-1],
        },
        {
            "name": "Uber Viz Diverging 1",
            "type": "diverging",
            "category": "Uber",
            "colors": ["#C22E00", "#EC9370", "#FEEEE8", "#85C4C8", "#00939C"][::-1],
        },
        {
            "name": "Uber Viz Diverging 1.5",
            "type": "diverging",
            "category": "Uber",
            "colors": [
                "#C22E00",
                "#DD7755",
                "#F8C0AA",
                "#BAE1E2",
                "#5DBABF",
                "#00939C",
            ][::-1],
        },
        {
            "name": "Uber Viz Diverging 2",
            "type": "diverging",
            "category": "Uber",
            "colors": [
                "#C22E00",
                "#E17449",
                "#F5B097",
                "#FEEEE8",
                "#A2D4D7",
                "#65B3BA",
                "#00939C",
            ][::-1],
        },
        {
            "name": "Uber Viz Diverging 2.5",
            "type": "diverging",
            "category": "Uber",
            "colors": [
                "#C22E00",
                "#D45F39",
                "#E68F71",
                "#F8C0AA",
                "#BAE1E2",
                "#7CC7CB",
                "#3EADB3",
                "#00939C",
            ][::-1],
        },
        {
            "name": "Uber Viz Diverging 3",
            "type": "diverging",
            "category": "Uber",
            "colors": [
                "#C22E00",
                "#DA6436",
                "#EC9370",
                "#F8C0AA",
                "#FEEEE8",
                "#B2DCDF",
                "#65B3BA",
                "#49A6AE",
                "#00939C",
            ][::-1],
        },
        {
            "name": "Uber Viz Diverging 3.5",
            "type": "diverging",
            "category": "Uber",
            "colors": [
                "#C22E00",
                "#D0532B",
                "#DD7755",
                "#EB9C80",
                "#F8C0AA",
                "#BAE1E2",
                "#8CCED1",
                "#5DBABF",
                "#2FA7AE",
                "#00939C",
            ][::-1],
        },
        {
            "name": "Uber Viz Diverging 4",
            "type": "diverging",
            "category": "Uber",
            "colors": [
                "#C22E00",
                "#D55A2B",
                "#E68059",
                "#F2A587",
                "#F8C0AA",
                "#FEEEE8",
                "#BAE1E2",
                "#97CED1",
                "#71BABF",
                "#49A6AE",
                "#00939C",
            ][::-1],
        },
    ],
}

color_ranges = {
    ColorRangeType.sequential: sequential_colors,
    ColorRangeType.diverging: diverging_colors,
    ColorRangeType.qualitative: qualitative_colors,
    ColorRangeType.single_hue: single_hue_colors,
}