"""Change to scenario deleted_ datatype to BigInt

Revision ID: 0856e32a76ad
Revises: 16288b174f62
Create Date: 2021-07-28 08:48:23.504534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0856e32a76ad'
down_revision = '16288b174f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario', 'deleted_pois',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BIGINT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_ways',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BIGINT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_buildings',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BIGINT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario', 'deleted_buildings',
               existing_type=sa.ARRAY(sa.BIGINT()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_ways',
               existing_type=sa.ARRAY(sa.BIGINT()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_pois',
               existing_type=sa.ARRAY(sa.BIGINT()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    # ### end Alembic commands ###
