"""Add scenario table

Revision ID: 16288b174f62
Revises: cd4e71f23c8d
Create Date: 2021-07-28 08:41:31.151463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16288b174f62'
down_revision = 'cd4e71f23c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('deleted_pois', sa.ARRAY(sa.Integer()), server_default='{}', nullable=True),
    sa.Column('deleted_ways', sa.ARRAY(sa.Integer()), server_default='{}', nullable=True),
    sa.Column('deleted_buildings', sa.ARRAY(sa.Integer()), server_default='{}', nullable=True),
    sa.Column('ways_heatmap_computed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_id'), 'scenario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_id'), table_name='scenario')
    op.drop_table('scenario')
    # ### end Alembic commands ###
