"""Change to scenario deleted_ datatype to BigInt __

Revision ID: 7c700d03969b
Revises: 0856e32a76ad
Create Date: 2021-07-28 08:56:01.515269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c700d03969b'
down_revision = '0856e32a76ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('scenario', 'deleted_pois',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_ways',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_buildings',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario', 'deleted_buildings',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.BIGINT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_ways',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.BIGINT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_pois',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.BIGINT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))

    # ### end Alembic commands ###
