"""Change to scenario deleted_ datatype to BigInt __

Revision ID: 91e7db9c91df
Revises: 7c700d03969b
Create Date: 2021-07-28 08:59:12.376227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91e7db9c91df'
down_revision = '7c700d03969b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.alter_column('scenario', 'deleted_pois',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.BIGINT(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_ways',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.BIGINT(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_buildings',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BIGINT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario', 'deleted_buildings',
               existing_type=sa.ARRAY(sa.BIGINT()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_ways',
               existing_type=sa.BIGINT(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.alter_column('scenario', 'deleted_pois',
               existing_type=sa.BIGINT(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::integer[]"))
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
