"""Add isochrone table with geom

Revision ID: cd4e71f23c8d
Revises: 49039ddc5d7a
Create Date: 2021-07-28 07:04:54.024597

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry


# revision identifiers, used by Alembic.
revision = 'cd4e71f23c8d'
down_revision = '49039ddc5d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('isochrone', sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('isochrone', 'geom')
    # ### end Alembic commands ###
