apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-celery-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goat-celery-flower
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: goat-celery-flower
    spec:
      containers:
        - image: mher/flower
          imagePullPolicy: IfNotPresent
          name: goat-celery-flower
          envFrom:
            - configMapRef:
                name: goat-celery-flower-config
          ports:
            - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: goat-celery-flower-service
spec:
  ports:
    - port: 80
      targetPort: 5555
  type: NodePort
  selector:
    app: goat-celery-flower
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: goat-celery-flower-config
  labels:
    app: goat-celery-flower
data:
  CELERY_BROKER_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@goat-rabbitmq-service:5672/goat
  FLOWER_BASIC_AUTH: ${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}
  FLOWER_URL_PREFIX: flower