apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-goat-plan4better-de
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - 'dev.goat.plan4better.de'
    secretName: dev-goat-plan4better-de-tls
  rules:
  - host: 'dev.goat.plan4better.de'
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: goat-api
              port:
                number: 80
        - path: /flower
          pathType: Prefix
          backend:
            service:
              name: goat-celery-flower-service
              port:
                number: 80
        - path: /rabbitmq
          pathType: Prefix
          backend:
            service:
              name: goat-rabbitmq-service
              port:
                number: 15672
        - path: /
          pathType: Prefix
          backend:
            service:
              name: goat-client
              port:
                number: 80