apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goat-redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: goat-redis
    spec:
      containers:
        - image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          name: goat-redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: goat-redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: goat-redis