apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:  
  namespace: ${NAMESPACE}
  name: postgres-service
spec:
  type: ExternalName
  externalName:  ${POSTGRES_HOST}