"""Added job id to layers

Revision ID: 006ee6ccdb7d
Revises: 15c48bccb3db
Create Date: 2024-01-15 06:45:59.742410

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006ee6ccdb7d'
down_revision = '15c48bccb3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=True), schema='customer')
    op.create_foreign_key(None, 'layer', 'job', ['job_id'], ['id'], source_schema='customer', referent_schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'layer', schema='customer', type_='foreignkey')
    op.drop_column('layer', 'job_id', schema='customer')
    # ### end Alembic commands ###
