"""Added trigger scenario id

Revision ID: 08a39337855a
Revises: b3deefd18a9f
Create Date: 2024-07-11 11:38:59.091420

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08a39337855a'
down_revision = 'b3deefd18a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('active_scenario_id', postgresql.UUID(as_uuid=True), nullable=True), schema='customer')
    op.alter_column('scenario_feature', 'geom',
               existing_type=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=True,
               schema='customer')
    op.drop_index('idx_scenario_feature_geom', table_name='scenario_feature', schema='customer', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_scenario_feature_geom', 'scenario_feature', ['geom'], unique=False, schema='customer', postgresql_using='gist')
    op.alter_column('scenario_feature', 'geom',
               existing_type=geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=False,
               schema='customer')
    op.drop_column('project', 'active_scenario_id', schema='customer')
    # ### end Alembic commands ###
