"""change

Revision ID: 0ef82409cd65
Revises: 59933f8e0172
Create Date: 2023-09-28 12:51:40.703431

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '0ef82409cd65'
down_revision = '59933f8e0172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
