"""Renamed indicator to tool

Revision ID: 15c48bccb3db
Revises: 091e369aa04f
Create Date: 2023-12-09 19:33:26.359522

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '15c48bccb3db'
down_revision = '091e369aa04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('tool_type', sa.Text(), nullable=True), schema='customer')
    op.drop_column('layer', 'indicator_type', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('indicator_type', sa.TEXT(), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('layer', 'tool_type', schema='customer')
    # ### end Alembic commands ###
