"""Add System Table for Cron

Revision ID: 178107e73b4d
Revises: 0ef9d166358c
Create Date: 2024-04-11 15:08:13.463785

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '178107e73b4d'
down_revision = '0ef9d166358c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_task',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.drop_index('idx_layer_extent', table_name='layer', schema='customer', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_layer_extent', 'layer', ['extent'], unique=False, schema='customer', postgresql_using='gist')
    op.drop_table('system_task', schema='customer')
    # ### end Alembic commands ###
