"""Added delete cascade for layer project

Revision ID: 264cec4f0280
Revises: efb2fb4a9bf8
Create Date: 2024-01-26 09:43:57.980903

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '264cec4f0280'
down_revision = 'efb2fb4a9bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('layer_project_layer_id_fkey', 'layer_project', schema='customer', type_='foreignkey')
    op.drop_constraint('layer_project_project_id_fkey', 'layer_project', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'layer_project', 'layer', ['layer_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.create_foreign_key(None, 'layer_project', 'project', ['project_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'layer_project', schema='customer', type_='foreignkey')
    op.drop_constraint(None, 'layer_project', schema='customer', type_='foreignkey')
    op.create_foreign_key('layer_project_project_id_fkey', 'layer_project', 'project', ['project_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.create_foreign_key('layer_project_layer_id_fkey', 'layer_project', 'layer', ['layer_id'], ['id'], source_schema='customer', referent_schema='customer')
    # ### end Alembic commands ###
