"""added read column to job

Revision ID: 40e85769889a
Revises: 83428b674a64
Create Date: 2023-09-28 16:02:00.244471

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '40e85769889a'
down_revision = '83428b674a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('read', sa.Boolean(), server_default='False', nullable=False), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'read', schema='customer')
    # ### end Alembic commands ###
