"""Add project_id in scenario table

Revision ID: 42adc620a8c5
Revises: f0bd558bbc7c
Create Date: 2024-06-06 16:07:48.338458

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42adc620a8c5'
down_revision = 'f0bd558bbc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False), schema='customer')
    op.create_foreign_key(None, 'scenario', 'project', ['project_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.add_column('scenario_feature', sa.Column('edit_type', sa.Text(), nullable=False), schema='customer')
    op.drop_column('scenario_feature', 'modification_type', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_feature', sa.Column('modification_type', sa.TEXT(), autoincrement=False, nullable=False), schema='customer')
    op.drop_column('scenario_feature', 'edit_type', schema='customer')
    op.drop_constraint(None, 'scenario', schema='customer', type_='foreignkey')
    op.drop_column('scenario', 'project_id', schema='customer')
    # ### end Alembic commands ###
