"""added project id to job

Revision ID: 4606dbed58be
Revises: 5a7dda5cf6a7
Create Date: 2023-09-29 06:37:46.113228

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4606dbed58be'
down_revision = '5a7dda5cf6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True), schema='customer')
    op.create_foreign_key(None, 'job', 'project', ['project_id'], ['id'], source_schema='customer', referent_schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', schema='customer', type_='foreignkey')
    op.drop_column('job', 'project_id', schema='customer')
    # ### end Alembic commands ###
