"""CHeck

Revision ID: 50a46e72e577
Revises: 9956913ab521
Create Date: 2024-09-17 18:41:24.985023

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '50a46e72e577'
down_revision = '9956913ab521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folder_user_id_fkey', 'folder', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'folder', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='accounts', ondelete='CASCADE')
    op.drop_constraint('job_user_id_fkey', 'job', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='accounts', ondelete='CASCADE')
    op.drop_constraint('layer_user_id_fkey', 'layer', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'layer', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='accounts', ondelete='CASCADE')
    op.drop_constraint('project_user_id_fkey', 'project', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='accounts', ondelete='CASCADE')
    op.drop_constraint('scenario_user_id_fkey', 'scenario', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'scenario', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='accounts', ondelete='CASCADE')
    op.drop_constraint('system_setting_user_id_fkey', 'system_setting', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'system_setting', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='accounts', ondelete='CASCADE')
    op.drop_constraint('user_project_user_id_fkey', 'user_project', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'user_project', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='accounts', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_project', schema='customer', type_='foreignkey')
    op.create_foreign_key('user_project_user_id_fkey', 'user_project', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_constraint(None, 'system_setting', schema='customer', type_='foreignkey')
    op.create_foreign_key('system_setting_user_id_fkey', 'system_setting', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_constraint(None, 'scenario', schema='customer', type_='foreignkey')
    op.create_foreign_key('scenario_user_id_fkey', 'scenario', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_constraint(None, 'project', schema='customer', type_='foreignkey')
    op.create_foreign_key('project_user_id_fkey', 'project', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_constraint(None, 'layer', schema='customer', type_='foreignkey')
    op.create_foreign_key('layer_user_id_fkey', 'layer', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_constraint(None, 'job', schema='customer', type_='foreignkey')
    op.create_foreign_key('job_user_id_fkey', 'job', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_constraint(None, 'folder', schema='customer', type_='foreignkey')
    op.create_foreign_key('folder_user_id_fkey', 'folder', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###
