"""added user_id to job

Revision ID: 5a7dda5cf6a7
Revises: 40e85769889a
Create Date: 2023-09-29 05:51:59.256556

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a7dda5cf6a7'
down_revision = '40e85769889a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False), schema='customer')
    op.create_foreign_key(None, 'job', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', schema='customer', type_='foreignkey')
    op.drop_column('job', 'user_id', schema='customer')
    # ### end Alembic commands ###
