"""add builder_config column

Revision ID: 70bf9033bd58
Revises: f3660efddfc9
Create Date: 2024-12-20 09:38:53.227648

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70bf9033bd58'
down_revision = 'f3660efddfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('builder_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'builder_config', schema='customer')
    # ### end Alembic commands ###
