"""added unique constraint

Revision ID: 75cf33b23b20
Revises: ea5778b147c4
Create Date: 2023-09-04 11:54:55.012901

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '75cf33b23b20'
down_revision = 'ea5778b147c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_layer_project', 'layer_project', ['layer_id', 'project_id'], schema='customer')
    op.create_unique_constraint('unique_user_project', 'user_project', ['project_id', 'user_id'], schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_project', 'user_project', schema='customer', type_='unique')
    op.drop_constraint('unique_layer_project', 'layer_project', schema='customer', type_='unique')
    # ### end Alembic commands ###
