"""Added response column to job

Revision ID: 7caf7de0c973
Revises: 4606dbed58be
Create Date: 2023-10-15 09:48:27.984656

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7caf7de0c973'
down_revision = '4606dbed58be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'response', schema='customer')
    # ### end Alembic commands ###
