"""added parameter column instead of style

Revision ID: 80405eff241d
Revises: 579c4d15bdea
Create Date: 2023-11-15 07:24:12.887191

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80405eff241d'
down_revision = '579c4d15bdea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('parameter', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    op.drop_column('layer', 'style', schema='customer')
    op.add_column('layer_project', sa.Column('parameter', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    op.drop_constraint('unique_layer_project', 'layer_project', schema='customer', type_='unique')
    op.drop_column('layer_project', 'style', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer_project', sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='customer')
    op.create_unique_constraint('unique_layer_project', 'layer_project', ['layer_id', 'project_id'], schema='customer')
    op.drop_column('layer_project', 'parameter', schema='customer')
    op.add_column('layer', sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('layer', 'parameter', schema='customer')
    # ### end Alembic commands ###
