"""change id of system_settings

Revision ID: 83428b674a64
Revises: deb9335c2e74
Create Date: 2023-09-28 14:23:16.121887

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '83428b674a64'
down_revision = 'deb9335c2e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'system_setting', 'user', ['user_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_setting', schema='customer', type_='foreignkey')
    # ### end Alembic commands ###
