"""extended layer project schemas

Revision ID: 8696fa293faa
Revises: d46792a0b773
Create Date: 2023-11-15 14:43:11.772902

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8696fa293faa'
down_revision = 'd46792a0b773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('other_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    op.drop_column('layer', 'parameter', schema='customer')
    op.add_column('layer_project', sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    op.add_column('layer_project', sa.Column('other_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    op.add_column('layer_project', sa.Column('z_index', sa.Integer(), nullable=True), schema='customer')
    op.drop_column('layer_project', 'parameter', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer_project', sa.Column('parameter', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('layer_project', 'z_index', schema='customer')
    op.drop_column('layer_project', 'other_properties', schema='customer')
    op.drop_column('layer_project', 'properties', schema='customer')
    op.add_column('layer', sa.Column('parameter', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('layer', 'other_properties', schema='customer')
    op.drop_column('layer', 'properties', schema='customer')
    # ### end Alembic commands ###
