"""Added status column

Revision ID: 8a4322891019
Revises: 61155cc2a758
Create Date: 2024-09-20 12:40:28.151046

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '8a4322891019'
down_revision = '61155cc2a758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('status', sa.Text(), nullable=False), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'status', schema='customer')
    # ### end Alembic commands ###
