"""add ondelete=cascade to scenario_feature.layer_id fk

Revision ID: 926f1fb79987
Revises: 42adc620a8c5
Create Date: 2024-06-07 07:39:51.250166

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '926f1fb79987'
down_revision = '42adc620a8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario_feature', 'layer_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='customer')
    op.drop_constraint('scenario_feature_layer_id_fkey', 'scenario_feature', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'scenario_feature', 'layer', ['layer_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario_feature', schema='customer', type_='foreignkey')
    op.create_foreign_key('scenario_feature_layer_id_fkey', 'scenario_feature', 'layer', ['layer_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.alter_column('scenario_feature', 'layer_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='customer')
    # ### end Alembic commands ###
