"""add project basemap column

Revision ID: 963ff8fb657b
Revises: 49b9ed64d5a7
Create Date: 2025-02-19 17:07:47.934698

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '963ff8fb657b'
down_revision = '49b9ed64d5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('basemap', sa.Text(), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'basemap', schema='customer')
    # ### end Alembic commands ###
