"""Removed foreign key for job table

Revision ID: 9b1ad1c7e70a
Revises: 264cec4f0280
Create Date: 2024-02-03 13:51:18.100746

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '9b1ad1c7e70a'
down_revision = '264cec4f0280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_job_test_layer_ids', table_name='job', schema='customer')
    op.drop_index('ix_customer_job_test_status_simple', table_name='job', schema='customer')
    op.drop_constraint('job_project_id_fkey', 'job', schema='customer', type_='foreignkey')
    op.drop_constraint('layer_job_id_fkey', 'layer', schema='customer', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('layer_job_id_fkey', 'layer', 'job', ['job_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.create_foreign_key('job_project_id_fkey', 'job', 'project', ['project_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.create_index('ix_customer_job_test_status_simple', 'job', ['status_simple'], unique=False, schema='customer')
    op.create_index('ix_customer_job_test_layer_ids', 'job', ['layer_ids'], unique=False, schema='customer')
    # ### end Alembic commands ###
