"""added column for feature geometry type

Revision ID: b1a9547c023b
Revises: 5905b5ccb86a
Create Date: 2023-08-09 13:46:11.024082

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'b1a9547c023b'
down_revision = '5905b5ccb86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('feature_layer_geometry_type', sa.Text(), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'feature_layer_geometry_type', schema='customer')
    # ### end Alembic commands ###
