"""added message simplified to job table

Revision ID: b3deefd18a9f
Revises: 926f1fb79987
Create Date: 2024-06-09 11:41:20.948357

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3deefd18a9f'
down_revision = '926f1fb79987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('msg_simple', sa.Text(), nullable=True), schema='customer')
    op.drop_column('job', 'response', schema='customer')
    op.drop_column('job', 'payload', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False), schema='customer')
    op.add_column('job', sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('job', 'msg_simple', schema='customer')
    # ### end Alembic commands ###
