"""created job table

Revision ID: c10bc2e3e748
Revises: 75cf33b23b20
Create Date: 2023-09-17 10:38:14.126738

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c10bc2e3e748'
down_revision = '75cf33b23b20'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('analysis_request', schema='customer')
    op.drop_table('table_mapping', schema='customer')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('layer_ids', sa.ARRAY(postgresql.UUID()), nullable=True),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_job_layer_ids'), 'job', ['layer_ids'], unique=False, schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_job_layer_ids'), table_name='job', schema='customer')
    op.drop_table('job', schema='customer')
    # ### end Alembic commands ###
