"""change project_layer to layer_project

Revision ID: d376083e8c61
Revises: 6ca82e410f39
Create Date: 2024-07-21 11:51:25.475468

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'd376083e8c61'
down_revision = '6ca82e410f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_feature', sa.Column('layer_project_id', sa.Integer(), nullable=False), schema='customer')
    op.drop_constraint('scenario_feature_project_layer_id_fkey', 'scenario_feature', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'scenario_feature', 'layer_project', ['layer_project_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_column('scenario_feature', 'project_layer_id', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_feature', sa.Column('project_layer_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='customer')
    op.drop_constraint(None, 'scenario_feature', schema='customer', type_='foreignkey')
    op.create_foreign_key('scenario_feature_project_layer_id_fkey', 'scenario_feature', 'layer_project', ['project_layer_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_column('scenario_feature', 'layer_project_id', schema='customer')
    # ### end Alembic commands ###
