"""removed legend urls

Revision ID: d46792a0b773
Revises: 80405eff241d
Create Date: 2023-11-15 08:42:32.951553

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd46792a0b773'
down_revision = '80405eff241d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'legend_urls', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('legend_urls', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True), schema='customer')
    # ### end Alembic commands ###
