"""Added in catalog column

Revision ID: d66308c155e0
Revises: 9b1ad1c7e70a
Create Date: 2024-03-02 15:56:27.095496

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'd66308c155e0'
down_revision = '9b1ad1c7e70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('in_catalog', sa.Boolean(), server_default='False', nullable=False), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'in_catalog', schema='customer')
    # ### end Alembic commands ###
