"""change id of system_settings

Revision ID: deb9335c2e74
Revises: 0ef82409cd65
Create Date: 2023-09-28 14:01:14.824959

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'deb9335c2e74'
down_revision = '0ef82409cd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
