"""made  z_index not nullable

Revision ID: e89bad838064
Revises: 8696fa293faa
Create Date: 2023-11-15 14:49:57.589561

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'e89bad838064'
down_revision = '8696fa293faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layer_project', 'z_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layer_project', 'z_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='customer')
    # ### end Alembic commands ###
