"""Change layer_id to project_layer_id

Revision ID: e99c8bdebbf7
Revises: 08a39337855a
Create Date: 2024-07-14 22:57:23.698353

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e99c8bdebbf7'
down_revision = '08a39337855a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_feature', sa.Column('project_layer_id', sa.Integer(), nullable=False), schema='customer')
    op.drop_constraint('scenario_feature_layer_id_fkey', 'scenario_feature', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'scenario_feature', 'layer_project', ['project_layer_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_column('scenario_feature', 'layer_id', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_feature', sa.Column('layer_id', postgresql.UUID(), autoincrement=False, nullable=False), schema='customer')
    op.drop_constraint(None, 'scenario_feature', schema='customer', type_='foreignkey')
    op.create_foreign_key('scenario_feature_layer_id_fkey', 'scenario_feature', 'layer', ['layer_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.drop_column('scenario_feature', 'project_layer_id', schema='customer')
    # ### end Alembic commands ###
