"""added status simple column

Revision ID: e9b61410359c
Revises: 7caf7de0c973
Create Date: 2023-10-15 11:54:14.792778

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'e9b61410359c'
down_revision = '7caf7de0c973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('status_simple', sa.Text(), nullable=False), schema='customer')
    op.create_index(op.f('ix_customer_job_status_simple'), 'job', ['status_simple'], unique=False, schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_job_status_simple'), table_name='job', schema='customer')
    op.drop_column('job', 'status_simple', schema='customer')
    # ### end Alembic commands ###
