"""Added additional metadata layer table

Revision ID: efb2fb4a9bf8
Revises: 006ee6ccdb7d
Create Date: 2024-01-22 13:17:36.929126

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'efb2fb4a9bf8'
down_revision = '006ee6ccdb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('lineage', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('positional_accuracy', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('attribute_accuracy', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('completeness', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('upload_reference_system', sa.Integer(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('upload_file_type', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('geographical_code', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('language_code', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('distributor_name', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('distributor_email', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('distribution_url', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('license', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('attribution', sa.Text(), nullable=True), schema='customer')
    op.add_column('layer', sa.Column('data_category', sa.Text(), nullable=True), schema='customer')
    op.drop_column('layer', 'data_source', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('data_source', sa.TEXT(), autoincrement=False, nullable=True), schema='customer')
    op.drop_column('layer', 'data_category', schema='customer')
    op.drop_column('layer', 'attribution', schema='customer')
    op.drop_column('layer', 'license', schema='customer')
    op.drop_column('layer', 'distribution_url', schema='customer')
    op.drop_column('layer', 'distributor_email', schema='customer')
    op.drop_column('layer', 'distributor_name', schema='customer')
    op.drop_column('layer', 'language_code', schema='customer')
    op.drop_column('layer', 'geographical_code', schema='customer')
    op.drop_column('layer', 'upload_file_type', schema='customer')
    op.drop_column('layer', 'upload_reference_system', schema='customer')
    op.drop_column('layer', 'completeness', schema='customer')
    op.drop_column('layer', 'attribute_accuracy', schema='customer')
    op.drop_column('layer', 'positional_accuracy', schema='customer')
    op.drop_column('layer', 'lineage', schema='customer')
    # ### end Alembic commands ###
