"""remove scenario_id and scenario_type from layer table

Revision ID: f0bd558bbc7c
Revises: 9062cfa17edc
Create Date: 2024-06-06 12:18:26.617438

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0bd558bbc7c'
down_revision = '9062cfa17edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('layer_scenario_id_fkey', 'layer', schema='customer', type_='foreignkey')
    op.drop_column('layer', 'scenario_type', schema='customer')
    op.drop_column('layer', 'scenario_id', schema='customer')
    op.add_column('scenario_feature', sa.Column('modification_type', sa.Text(), nullable=False), schema='customer')
    op.alter_column('scenario_feature', 'feature_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='customer')
    op.drop_column('scenario_feature', 'scenario_type', schema='customer')
    op.alter_column('scenario_scenario_feature', 'scenario_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='customer')
    op.alter_column('scenario_scenario_feature', 'scenario_feature_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='customer')
    op.drop_constraint('scenario_scenario_feature_scenario_id_fkey', 'scenario_scenario_feature', schema='customer', type_='foreignkey')
    op.drop_constraint('scenario_scenario_feature_scenario_feature_id_fkey', 'scenario_scenario_feature', schema='customer', type_='foreignkey')
    op.create_foreign_key(None, 'scenario_scenario_feature', 'scenario_feature', ['scenario_feature_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    op.create_foreign_key(None, 'scenario_scenario_feature', 'scenario', ['scenario_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario_scenario_feature', schema='customer', type_='foreignkey')
    op.drop_constraint(None, 'scenario_scenario_feature', schema='customer', type_='foreignkey')
    op.create_foreign_key('scenario_scenario_feature_scenario_feature_id_fkey', 'scenario_scenario_feature', 'scenario_feature', ['scenario_feature_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.create_foreign_key('scenario_scenario_feature_scenario_id_fkey', 'scenario_scenario_feature', 'scenario', ['scenario_id'], ['id'], source_schema='customer', referent_schema='customer')
    op.alter_column('scenario_scenario_feature', 'scenario_feature_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='customer')
    op.alter_column('scenario_scenario_feature', 'scenario_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='customer')
    op.add_column('scenario_feature', sa.Column('scenario_type', sa.TEXT(), autoincrement=False, nullable=False), schema='customer')
    op.alter_column('scenario_feature', 'feature_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='customer')
    op.drop_column('scenario_feature', 'modification_type', schema='customer')
    op.add_column('layer', sa.Column('scenario_id', postgresql.UUID(), autoincrement=False, nullable=True), schema='customer')
    op.add_column('layer', sa.Column('scenario_type', sa.TEXT(), autoincrement=False, nullable=True), schema='customer')
    op.create_foreign_key('layer_scenario_id_fkey', 'layer', 'scenario', ['scenario_id'], ['id'], source_schema='customer', referent_schema='customer')
    # ### end Alembic commands ###
