"""add max_extent column

Revision ID: f3660efddfc9
Revises: 8a4322891019
Create Date: 2024-12-12 09:53:03.741447

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'f3660efddfc9'
down_revision = '8a4322891019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('max_extent', sa.ARRAY(sa.Float()), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'max_extent', schema='customer')
    # ### end Alembic commands ###
