"""Add column length in EPSG 3857

Revision ID: 199ee7bfd0ef
Revises: d439f1a84c69
Create Date: 2022-01-26 15:47:33.617409

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '199ee7bfd0ef'
down_revision = 'd439f1a84c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('length_3857', sa.Float(precision=53), nullable=True), schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edge', 'length_3857', schema='basic')
    # ### end Alembic commands ###
