"""Add json column edge

Revision ID: 4bc228ef23f2
Revises: 6f27040e0285
Create Date: 2022-01-26 13:43:06.025037

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bc228ef23f2'
down_revision = '6f27040e0285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('coordinates_3857', postgresql.JSON(astext_type=sa.Text()), nullable=True), schema='basic')
    op.drop_column('edge', 'geom_3857', schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('geom_3857', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=3857, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=False), schema='basic')
    op.drop_column('edge', 'coordinates_3857', schema='basic')
    # ### end Alembic commands ###
