"""added table study_area

Revision ID: 59c89526c553
Revises: c77f1430b254
Create Date: 2022-01-22 15:07:08.125617

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '59c89526c553'
down_revision = 'c77f1430b254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='basic'
    )
    op.create_index('idx_study_area_geom', 'study_area', ['geom'], unique=False, schema='basic', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_study_area_geom', table_name='study_area', schema='basic', postgresql_using='gist')
    op.drop_table('study_area', schema='basic')
    # ### end Alembic commands ###
