"""added table grid_visualization_parameter

Revision ID: 685f10cd9624
Revises: d55ace55b04b
Create Date: 2022-01-22 15:19:13.110106

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '685f10cd9624'
down_revision = 'd55ace55b04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_visualization_parameter',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('area_isochrone', sa.Float(precision=53), nullable=True),
    sa.Column('percentile_area_isochrone', sa.SmallInteger(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('percentile_population', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['basic.grid_visualization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='basic'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grid_visualization_parameter', schema='basic')
    # ### end Alembic commands ###
