"""Init db schema

Revision ID: 96e8ab19a2ae
Revises: 
Create Date: 2022-01-23 11:14:09.231051

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96e8ab19a2ae'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema basic")
    op.execute("create schema customer")
    op.execute("create schema extra")
    op.execute("create schema temporal")
    public_alembic_version_replicator_select = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='replicator', grant='SELECT', with_grant_option=False)
    op.drop_entity(public_alembic_version_replicator_select)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_alembic_version_replicator_select = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='replicator', grant='SELECT', with_grant_option=False)
    op.create_entity(public_alembic_version_replicator_select)
    op.execute("drop schema basic")
    op.execute("drop schema customer")
    op.execute("drop schema extra")
    op.execute("drop schema temporal")
    # ### end Alembic commands ###