"""Made coordinates_3857 not nullable

Revision ID: d439f1a84c69
Revises: 4bc228ef23f2
Create Date: 2022-01-26 13:46:20.250596

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd439f1a84c69'
down_revision = '4bc228ef23f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edge', 'coordinates_3857',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edge', 'coordinates_3857',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='basic')
    # ### end Alembic commands ###
