"""added table grid_visualization

Revision ID: d55ace55b04b
Revises: a6ce5b9ffb4e
Create Date: 2022-01-22 15:11:42.134199

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd55ace55b04b'
down_revision = 'a6ce5b9ffb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_visualization',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='basic'
    )
    op.create_index('idx_grid_visualization_geom', 'grid_visualization', ['geom'], unique=False, schema='basic', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_grid_visualization_geom', table_name='grid_visualization', schema='basic', postgresql_using='gist')
    op.drop_table('grid_visualization', schema='basic')
    # ### end Alembic commands ###
