CREATE OR REPLACE FUNCTION basic.uuid_generate_v7()
RETURNS UUID
AS $$
BEGIN
  -- USE RANDOM V4 UUID AS STARTING POINT (WHICH HAS THE SAME VARIANT WE NEED)
  -- THEN OVERLAY TIMESTAMP
  -- THEN SET VERSION 7 BY FLIPPING THE 2 AND 1 BIT IN THE VERSION 4 STRING
  RETURN ENCODE(
    SET_BIT(
      SET_BIT(
        OVERLAY(UUID_SEND(GEN_RANDOM_UUID())
                PLACING SUBSTRING(INT8SEND(FLOOR(EXTRACT(EPOCH FROM CLOCK_TIMESTAMP()) * 1000)::BIGINT) FROM 3)
                FROM 1 FOR 6
        ),
        52, 1
      ),
      53, 1
    ),
    'hex')::UUID;
END
$$
LANGUAGE plpgsql
VOLATILE;